### ISSUE TITLE
AMDP Code need be pretty print?

### ISSUE THREAD

**Issue by songzc3** [SAP/abap-cleaner#108]
I find AMDP code can not be pretty print? It works  on abap code,not sql code?

**Comment by ConjuringCoffee** [comment]
AMDP isn't ABAP, it's SQL script 😬

**Comment by jmgrassau** [comment]
Hi songzc3 and ConjuringCoffee, 

yes, exactly – this would basically mean adding support for another programming language … 

The idea already came up in the Inner-Source phase and is even reflected in the README's section on [Upcoming Changes](https://github.com/SAP/abap-cleaner#upcoming-changes), but I'm afraid for now, that's out of scope. 

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
I assume this approach would apply to CDS views as well? Also not ABAP but would be very useful.

**Comment by songzc3** [comment]
> Hi songzc3 and ConjuringCoffee,
> 
> yes, exactly – this would basically mean adding support for another programming language …
> 
> The idea already came up in the Inner-Source phase and is even reflected in the README's section on [Upcoming Changes](https://github.com/SAP/abap-cleaner#upcoming-changes), but I'm afraid for now, that's out of scope.
> 
> Kind regards, Jörg-Michael

Thanks for jmgrassau's reply. I hope this function is coming soon .It is very useful for AMDP maintaince for me.

**Comment by jmgrassau** [comment]
Hi @jelliottp,

as you maybe already noted in the [Release Notes](https://github.com/SAP/abap-cleaner/blob/main/docs/release-notes.md) for  version 1.19.1, formatting of CDS views is now supported with 21 new cleanup rules! :-) 

However, no news on AMDP / SQL Script, unfortunately, therefore keeping this issue "out of scope". 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Thanks for the transparency!
