### ISSUE TITLE
Mini bug--Convert lower case?

### ISSUE THREAD

**Issue by songzc3** [SAP/abap-cleaner#110]
I set variant to lower case,but it sound not work on field symbol .
![A8EQ5OSIH{Q6A(@ }C%H TX](https://github.com/SAP/abap-cleaner/assets/44917923/851496c7-be58-45c9-baf3-3a741f2d93db)
I think it's mini bug.
Now I just put shift +F1 ,and then CTRL+4 to clean abap code.

**Comment by jmgrassau** [comment]
Hi songzc3, 

please try deactivating the "Keep camel case identifiers" option in the ABAP cleaner rule "Convert upper and lower case", this should do the trick:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/012682bd-8bbd-4dc7-93ec-960f565afa7c)

Kind regards,
Jörg-Michael

**Comment by songzc3** [comment]
Thanks jmgrassau,it works.

**Comment by jmgrassau** [comment]
Hi songzc3, 

great – then I think I can close this issue.

Kind regards,
Jörg-Michael
