### ISSUE TITLE
Mutable table incorrectly changed to immutable, when accessed via table expression

### ISSUE THREAD

**Issue by bnichell** [SAP/abap-cleaner#112]
In following example, the keyword `DATA` is incorrectly changed to `FINAL`, if option "Use FINAL for immutable variables" is active:

```ABAP
CLASS lcl_test DEFINITION.
  PUBLIC SECTION.
    TYPES: BEGIN OF test_structure,
             a TYPE string,
             b TYPE string,
           END OF test_structure.
    TYPES test_table TYPE TABLE OF test_structure WITH DEFAULT KEY.

    METHODS returning_table RETURNING VALUE(result) TYPE test_table.

    METHODS handling_table.
ENDCLASS.



CLASS lcl_test IMPLEMENTATION.
  METHOD returning_table.
    result = VALUE #( ( a = 'a' b = 'b' ) ).
  ENDMETHOD.


  METHOD handling_table.
    DATA(mutable_table) = returning_table( ).    " <<<< changed to FINAL(mutable_table)
    mutable_table[ 1 ]-a = 'b'.
  ENDMETHOD.
ENDCLASS.
```

The incorrect change is reported in ADT with error message "The field "MUTABLE_TABLE" cannot be modified.".

**Comment by jmgrassau** [comment]
Hi bnichell, 

thanks a lot for reporting this – you're right, ABAP cleaner fails to identify the write position of ```mutable_table``` here! Will fix this asap.

Interestingly, while analyzing this, it seems that even attributes of referenced objects can't be changed if the table is immutable (here trying with a table that contains references to exception objects):

![image](https://github.com/SAP/abap-cleaner/assets/79639298/44a2bf25-29fb-4f01-b833-57847ba4428a)

Kind regards,
Jörg-Michael

**Comment by fabianlupa** [comment]
> Interestingly, while analyzing this, it seems that even attributes of referenced objects can't be changed if the table is immutable (here trying with a table that contains references to exception objects):
> 
> ![image](https://user-images.githubusercontent.com/79639298/270667364-44a2bf25-29fb-4f01-b833-57847ba4428a.png)

Surely that's a bug in the compiler? As this works just fine.

```abap
FINAL(no_immutable_objects_for_us) = NEW customer( ).
no_immutable_objects_for_us->name = 'John'.
```

**Comment by bnichell** [comment]
Hi Jörg-Michael,

thanks for the very quick fix.

Cheer,
Benedikt
