### ISSUE TITLE
Parse error: code mismatch with RND Parser output

### ISSUE THREAD

**Issue by oscardelama** [SAP/abap-cleaner#115]
Hi. I got the following error:

>  Parse error in line 90: code mismatch with RND Parser output
>  
> 1 entry was added to the error log 'C:\Users\me\AppData\Roaming\SAP\ABAP
  cleaner\user\error.log': the cleanup of a code file was cancelled

The log just says the same as the first line above.

The line 90 contains this:

>
    call_subrc = me->fake_debug_error->get_fake_subrc_exception(
      EXPORTING context = asynch_dispatch_subrc_context
                probability = '0.05'
                id = !task_to_execute-task_id
      IMPORTING sys_msg = sys_msg ).

I use the "!" character in `!task_to_execute` to denote a method parameter.

Where the called method has the following signature:

>
    METHODS get_fake_subrc_exception
      IMPORTING !subrc              TYPE sy-subrc DEFAULT 0
                !context            TYPE context
                !probability        TYPE f
                !id                 TYPE csequence
      EXPORTING !sys_msg            TYPE symsg
      RETURNING VALUE(result_subrc) TYPE sy-subrc.

Even when I hilight a snippet or a method, different to the one containing the issue above, I get the same error.

**Comment by jmgrassau** [comment]
Hi Oscar, 

ah, great, thanks for the hint! This was about the ```!task_to_execute-task_id```, where the RND Parser simply omits the ```!```, while ABAP cleaner keeps it (and then complained about the mismatch). ABAP cleaner already handled this correctly for simple identifiers such as ```!probability```, but not yet for composed ones like ```!task_to_execute-task_id```. It will be fixed in the next release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Oscar, 

thanks again for reporting this bug! This should now be fixed with version 1.6.0, which was just released.

Kind regards,
Jörg-Michael
