### ISSUE TITLE
Docs enhancement: Guide to use ABAP Cleaner in Github Workflow

### ISSUE THREAD

**Issue by stockbal** [SAP/abap-cleaner#127]
Hi Jörg-Michael,

I now got a first working version of a Github Action Workflow that uses ABAP Cleaner 😄.
As I am not a GitHub Workflow expert by far, I am not sure if it is the best approach to do it, but hey, it is working.

[Here](https://github.com/stockbal/abap-cleanup-test/blob/main/.github/workflows/clean-up.yml) is the workflow in my sample repository. I only had one minor hickup after the job first ran and I tried to import the changes back into my ABAP system.  
After a little bit of debugging I found the culprit... `crlf` 😋. abapGit is splitting the received text content from git at `lf` into an internal table. The left behind carriage return is then seen as unknown statement and the import fails.

In a local setup the `crlf` characters written by ABAP cleaner never caused this because of the git setting `core.autocrlf = true`. And luckily enough this can also be set inside the workflow. So an additional step before the checkout solved it.

```yaml
    - run: git config --global core.autocrlf true

    - name: Checkout
      uses: actions/checkout@v3
```
After that additional file changes via the workflow could be imported back to the ABAP system without any issue.

All the best,
Ludwig

**Comment by jmgrassau** [comment]
Hi Ludwig, 

that's amazing!! Hardly any GitHub Workflow knowledge on my side, but could you try changing the hard-coded release number into this: ```releases/download/v1.6.0/``` -> ```releases/latest/download/```

https://github.com/SAP/abap-cleaner/releases/latest/download/com.sap.adt.abapcleaner.app-linux.gtk.x86_64.tar.gz

> After a little bit of debugging I found the culprit...

Oops 😉 Yes, the world would be a better place without / versus \\ or ```crlf``` versus ```lf```…

Kind regards,
Jörg-Michael

**Comment by stockbal** [comment]
Hi Jörg-Michael,

Ah, I new there was a way to get the latest release 👍🚀 . Change is done, works like a charm.

Kind regards,
Ludwig

**Comment by jmgrassau** [comment]
Hi Ludwig, 

the [How to use ABAP cleaner](https://github.com/SAP/abap-cleaner/blob/main/docs/usage.md#how-to-use-abap-cleaner) documentation was now enhanced with a section on [GitHub Actions workflow usage](https://github.com/SAP/abap-cleaner/blob/main/docs/usage.md#github-actions-workflow-usage)! Hope this is as you expected it to be – otherwise please let me know. And again thanks so much for you contributions! 

Kind regards,
Jörg-Michael
