### ISSUE TITLE
Feature request: Make rule names copyable with ctrl+c  . 

### ISSUE THREAD

**Issue by JoachimRees** [SAP/abap-cleaner#130]
In the "Profile and Rules"-screen, it would be nice to have a way to copy (ctrl+c) the rule name. 
(Reason: if I can copy it, I don't have to type it...) 

Any way this is made possible is fine with me, 2 ways I can think of:

- Make it possible to select the title (1 in the screenshot) with the mouse. 
- When the rule (2 in the screenshot) is highlighted by click, make ctrl+c copy its text (as of now it seems to do nothing)

Other possible ways I can think of:
- right click on rule -> copy name to clipboard
- double click on rule -> open browser with page for that rule (I can copy from a browser). 

![2023-10-04 15_55_13-Profiles and Rules_howToCopy](https://github.com/SAP/abap-cleaner/assets/56995316/931e42d6-d384-40d6-b57a-1e18d8664e2f)

**Comment by jmgrassau** [comment]
Hi Joachim, 

great idea here, and this is now available with version 1.7.0, which was just released! Already used this many times myself :-) 

Kind regards,
Jörg-Michael
