### ISSUE TITLE
Custom configuration not displayed after 1.7.0 update

### ISSUE THREAD

**Issue by Lightirius** [SAP/abap-cleaner#138]
After update to version 1.7.0 from 1.6.0 custom profiles created in version 1.6.0 are missing.

Newly created/imported profiles are not displayed in the main "Profiles" list after clicking "Save Profiles and Exit" button and are not displayed on configuration screen after re-entering configuration

It looks like something is wrong with the default user profiles folder configuration. Path to the "Own Profiles" folder was blank after update. Moving it to some location and back to default location fixed profile display

I am using Eclipse 2023-09 with java 17.0.7

**Comment by jmgrassau** [comment]
Hi Lightirius, 

oh, that's not good at all! Thanks for reporting this so quickly, I will release a bug fix version 1.7.1 asap.

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Lightirius, 

okay, this is now fixed with version 1.7.1, which was just released. The profiles were not "lost", but rather not loaded. Let's hope not too many users were affected by this. Again, thanks for the quick bug report! 

Kind regards,
Jörg-Michael
