### ISSUE TITLE
Replacement rule for following logical expressions:  = space (or = '') to IS INITIAL and or <> space  (or <> '') to IS NOT INITIAL . 

### ISSUE THREAD

**Issue by prokopp80** [SAP/abap-cleaner#150]
Hi team,
would it be possible to impletent a replacement rule that replaces logical expressions like below (... there cases in which you evaluate non boolean variables)

Example: 
= space to IS INITIAL 
<> space to IS NOT INITIAL ...

Thank you,
Best regards Petr

**Comment by jmgrassau** [comment]
Hi Petr, 

I'm afraid this won't be possible, because ABAP cleaner does not do additional backend calls – which would be needed to determine the technical domain of the respective variable (e.g. if the domain is NUMC, then space isn't the initial value). 

Kind regards,
Jörg-Michael
