### ISSUE TITLE
Align conditional expressions: one-liners for SWITCH doesn't work as expected

### ISSUE THREAD

**Issue by GKaschke** [SAP/abap-cleaner#156]
Logic for SWITCH doesn't work as expected. COND is ok. For option: Create if possible

Example:
    " Pre <ctrl>-4
    r_rotated_inum = switch #( i_inum when 0 then 3 else ( i_inum - 1 ) ).
    r_rotated_inum = cond #( when i_inum is initial then 3 else ( i_inum - 1 ) ).

    " Post <ctrl>-4
    r_rotated_inum = switch #( i_inum
                               when 0 then 3 else ( i_inum - 1 ) ).
    r_rotated_inum = cond #( when i_inum is initial then 3 else ( i_inum - 1 ) ).

**Comment by jmgrassau** [comment]
Hi GKaschke, 

you're right, there is no reason why this should be kept on one line – thanks for opening this issue, will look into it!

Kind regards,
Jörg-Michael

**Comment by GKaschke** [comment]
Hello Jörg-Michael,
With the option "Create if possible" the SWITCH statement should be kept one line. As like as with COND.
Regards,
Günter

**Comment by jmgrassau** [comment]
Hello Günter, 

this will be fixed with the next release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Günter, 

thanks again for reporting this! These one-liners should work now with version 1.8.0, which was just released!

Kind regards,
Jörg-Michael
