### ISSUE TITLE
Feature Request: Indent RECEIVE RESULTS FROM FUNCTION correctly

### ISSUE THREAD

**Issue by fmabap** [SAP/abap-cleaner#166]
Hi,
the parameters and exceptions of the RECEIVE RESULTS FROM FUNCTION command are currently not indented correctly with the default profile. Can you please adjust it to indent them like at the CALL FUNCTION command?

Example:

```abap 
    RECEIVE RESULTS FROM FUNCTION mv_funcname
      IMPORTING
        et_para1               = et_para1
      ET_PARA2 = LT_PAR2
ET_PARA3 = LT_PARA3
      EXCEPTIONS
    system_failure        = 1
     communication_failure = 2
       OTHERS                = 3.
```
Current cleaning:

<img width="831" alt="image" src="https://github.com/SAP/abap-cleaner/assets/101019006/6f2e1a94-565d-4b98-acc3-fea9eff090d3">

Best regards
Frank

**Comment by jmgrassau** [comment]
Hi Frank, 

good point, this should be easy to include into the "Align parameters and components" rule!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Frank, 

voilà, this will be available (following the configuration of the "Align parameters and components" rule) in the next release:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/cc81af45-5739-4c42-9980-2e365b694771)

Kind regards,
Jörg-Michael

**Comment by fmabap** [comment]
Hi Jörg-Michael,

great, thank you!

I will leave the issue open until the next release.

Best regards
Frank

**Comment by jmgrassau** [comment]
Hi Frank, 

thanks again for opening this – RECEIVE RESULTS should now be aligned with version 1.8.0, which was just released!

Kind regards,
Jörg-Michael
