### ISSUE TITLE
Feature request: FORM definition alignment

### ISSUE THREAD

**Issue by duytai800** [SAP/abap-cleaner#168]
Hello Jörg-Michael! My request is for the FORM definitions to be aligned automatically. Thank you.

**Comment by jmgrassau** [comment]
Hi Tài, 

thanks a lot, taking this as further support for implementing #84 :-)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Tài,

as mentioned in #84, the new cleanup rule "Align FORM declarations" was just released with version 1.10.0! 

Kind regards,
Jörg-Michael
