### ISSUE TITLE
TODO does not respect table expressions

### ISSUE THREAD

**Issue by GKaschke** [SAP/abap-cleaner#169]
Hello,
I think in following lines the "prev_tabix" is required in "clear tplantboms[ prev_tabix ]-is_ltst." and can't removed.
Regards,
Günter

    " TODO: variable is assigned but never used (ABAP cleaner)
    data prev_tabix    type syst_tabix.
    data prev_plantbom like line of tplantboms.

    clear prev_tabix.
    loop at tplantboms reference into data(rl).
      data(tabix) = sy-tabix.
      if     rl->werks = prev_plantbom-werks
         and rl->stlnr = prev_plantbom-stlnr
         and rl->stlal = prev_plantbom-stlal.
        clear tplantboms[ prev_tabix ]-is_ltst.
      endif.
      prev_plantbom = rl->*.
      prev_tabix    = tabix.
    endloop.

**Comment by jmgrassau** [comment]
Hi Günter, 

ah, well spotted, thanks! This bug will be fixed in the next release.

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Günter, 

thanks again for reporting this bug! The issues should now be fixed in version 1.9.0, which was just released. 

Kind regards,
Jörg-Michael
