### ISSUE TITLE
PERFORM statements: alignment of parameters 

### ISSUE THREAD

**Issue by kaisicker** [SAP/abap-cleaner#171]
Hi,

so far the parameters of PERFORM statements are not aligned correctly: 
![image](https://github.com/SAP/abap-cleaner/assets/16294794/b5999666-b7e1-46c8-92d1-e997b7611e36)
It would be great to have this!

**Comment by jmgrassau** [comment]
Hi kaisicker, 

this is already requested in #83 – hope to be able to implement such a cleanup rule soon! 

Kind regards,
Jörg-Michael

**Comment by kaisicker** [comment]
Realizied too late that it was already requested. 
Thanks!

**Comment by jmgrassau** [comment]
Hi kaisicker,

as mentioned in #83, the new cleanup rule "Align PERFORM parameters" was just released with version 1.10.0!

Kind regards,
Jörg-Michael
