### ISSUE TITLE
Display issues in `Dark theme` after changing option of rule `Standardize CLASS ... DEFINITION`

### ISSUE THREAD

**Issue by bnichell** [SAP/abap-cleaner#179]
When the `Dark theme` is active, changing any option of rule `Standardize CLASS ... DEFINITION` leads to the background of the options being set to the same color as the text and thus the text is no longer readable.
The issue can be resolved by reopening the rule.

Other themes are not affected.

Before changing any option:
![image](https://github.com/SAP/abap-cleaner/assets/140068549/61f903f2-0a95-4c5c-8de5-8aac2bd59e90)

After changing any option:
![image](https://github.com/SAP/abap-cleaner/assets/140068549/4ca6ef78-3e1c-461c-8f72-0d99d9ba50b3)

**Comment by bnichell** [comment]
Hi Jörg-Michael,

supporting multi themes is always a pain, tell me about it... Thanks for the quick fix.

Cheers,
Benedikt

**Comment by jmgrassau** [comment]
Hi Benedikt, 

thanks again for reporting this bug – it should be fixed (and hopefully never come up again!) in version 1.10.0, which was just released!

Kind regards,
Jörg-Michael
