### ISSUE TITLE
Feature Request: Alignment of SELECT statements

### ISSUE THREAD

**Issue by kaisicker** [SAP/abap-cleaner#181]
It would be great if SELECT statements could be formatted as follows:
- 1 keyword per line (with option to have the FROM statement in first line)
- Indentation from second line (with option for 2/4 letters or alignment with second word from first line) 
- Use of FIELDS statement 

**Example:**
Original:
SELECT x y z FROM table
WHERE p = @p INTO result.

Result:
SELECT FROM table
................FIELDS x y z
................WHERE p = @p
................INTO result.

**Comment by jelliottp** [comment]
There would be a lot of value in having a rule for these to get some consistency. Although, it would need some customization options as I suspect there are a lot of different opinions on how it should be done.

For example, most of the time I apply this formatting (though parameters could be on one line).

```
SELECT x,
       y,
       z 
  FROM table
  INTO @result
  WHERE p = @p
    AND q = @q.
```

It would also be handy to have an option to add the escape characters to variables, we have checks for this now.

**Comment by ConjuringCoffee** [comment]
There's already an issue for this: https://github.com/SAP/abap-cleaner/issues/6 😉

**Comment by kaisicker** [comment]
> There's already an issue for this: #6 😉



> There's already an issue for this: #6 😉

I already wondered that no one had brought this up before:) I will close this one then.

**Comment by kaisicker** [comment]
Closed because it is a duplicate of https://github.com/SAP/abap-cleaner/issues/6
