### ISSUE TITLE
Filter Criteria error within a CDS Path Expression

### ISSUE THREAD

**Issue by Finbar-Callaghan** [SAP/abap-cleaner#190]
Hello,
Firstly and foremost, I love what you have achieved, well done!

I’ve observed the following fringe scenario with CDS Path Expressions while playing with Table Functions that generates an error status. I’ve written a number or permutations to work out the logic, which I hope helps.

Code written as a straight join, this is the baseline scenario to establish I wasn’t doing something stupid…
    SELECT Country, \_Text-CountryName, \_Text-NationalityName 
	FROM Z_FinCountryViaTableFunction
    	WHERE Country EQ 'AU'
    	AND  \_Text-Language = 'E'
     	INTO TABLE @DATA(lt_countrytext1).

 This is a sample of filter criteria in a path expression that works
    SELECT Country, \_Text[ (1) ]-CountryName,\_Text[ (1) ]-NationalityName 
	FROM Z_FinCountryViaTableFunction
    	WHERE Country EQ 'AU'
    	INTO TABLE @DATA(lt_countrytext3).

![image](https://github.com/SAP/abap-cleaner/assets/141810374/5b8097c6-0d09-4a4e-9edd-6faab6a37301)
*   These are samples of filter criteria in a path expression that regrettably do not work
    SELECT Country, \_Text[ INNER : WHERE Language = 'E' ]-NationalityName 
	FROM Z_FinCountryViaTableFunction
    	WHERE Country EQ 'AU'
     	INTO TABLE @DATA(lt_countrytext2).

    SELECT Country, \_Text[ (1) inner : where Language = 'E' ]-NationalityName as Text 
	FROM Z_FinCountryViaTableFunction
    	Where Country EQ 'AU'
    	INTO TABLE @DATA(lt_countrytext4).

And provides the following error
<img width="482" alt="image" src="https://github.com/SAP/abap-cleaner/assets/141810374/0a1d1d33-d0dc-449a-8b27-dd61cd225c09">

Thanking you in advance.

Regards,
Finbar

**Comment by jmgrassau** [comment]
Hi Finbar, 

actually this issue should have been fixed with version 1.7.0, could you check which version you are using? The examples should work with the current version:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/84330ca7-65e8-499a-a047-975732021731)

There is no deeper meaning to the colon in ```INNER : WHERE```, is there? This is what ABAP cleaner got confused about up to version 1.7.0.

Kind regards,
Jörg-Michael

**Comment by Finbar-Callaghan** [comment]
Jörg-Michael,
Thank you for the prompt response and you are correct, will update accordingly...
![image](https://github.com/SAP/abap-cleaner/assets/141810374/53e3ee7d-42e5-41f3-8c9e-8156470ff686)
All the best,
Finbar

**Comment by jmgrassau** [comment]
Hi Finbar, 

perfect, thanks a lot!

Kind regards,
Jörg-Michael
