### ISSUE TITLE
Feature request: Remove generated include headers

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#192]
Hi Jörg-Michael, I'd like to request the possibility to remove the generated include headers.

For example, when creating the include `ZEXAMPLE`:

```abap
*&---------------------------------------------------------------------*
*&  Include  zexample
*&---------------------------------------------------------------------*
```

(I'm currently reviewing code in which the name in the generated comment doesn't match the actual include name anymore.)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

absolutely – I think this could be part of the dedicated rule "Remove auto-generated comments" discussed in #152!

Kind regards,
Jörg-Michael
