### ISSUE TITLE
WHERE-statements different than IF-statements

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#193]
Hey,

is there any reason why the WHERE-statements are formatted different (in the example below: not at all) than the same statements put in an IF-clause?

![CleanShot 2023-11-09 at 16 11 43](https://github.com/SAP/abap-cleaner/assets/3112128/3ead8596-3405-43c9-ba85-0ddff133a8b5)

Thanks!

Regards,
Vlad

**Comment by ConjuringCoffee** [comment]
Hi Vlad, SQL statements are not supported yet. See: https://github.com/SAP/abap-cleaner/issues/6

**Comment by VladGhitulescu** [comment]
Thanks!

**Comment by jmgrassau** [comment]
Hi Vlad, 

actually working on this now, therefore reopening the issue :-)

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Hi Jörg-Michael, that's some exciting news! What can we expect here? Is this the start of fully supporting Open SQL? 😄

**Comment by jelliottp** [comment]
> Hi Jörg-Michael, that's some exciting news! What can we expect here? Is this the start of fully supporting Open SQL? 😄

Agree! Was just thinking about asking about the status of Open SQL formatting. It's probably the thing I most often still have to format manually.

**Comment by jmgrassau** [comment]
Hi Vlad, 

thanks for opening this issue! The cleanup rule "Align logical expressions" was now enhanced with the following options for ABAP SQL statements …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b5bb1f06-f3d0-451f-bfa8-ba87079d3008)

… and these enhancements were just released with version 1.12.0. 

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment]
Thanks a lot JM!
