### ISSUE TITLE
ENUM definitions are not aligned

### ISSUE THREAD

**Issue by kjetil-kilhavn** [SAP/abap-cleaner#194]
The following code is not changed at all by ABAP cleaner
```
    TYPES:
      BEGIN OF ENUM cost_distribution BASE TYPE vrtkz,
        not_distributed VALUE IS INITIAL,
        by_quantity VALUE '1',
        by_percentage VALUE '2',
        by_amount VALUE '3',
      END OF ENUM cost_distribution.
```

It would make sense that ABAP Cleaner aligns the VALUE parts of ENUMs, for instance as shown below
```
    TYPES:
      BEGIN OF ENUM cost_distribution BASE TYPE vrtkz,
        not_distributed VALUE IS INITIAL,
        by_quantity     VALUE '1',
        by_percentage   VALUE '2',
        by_amount       VALUE '3',
      END OF ENUM cost_distribution.
```

**Comment by jmgrassau** [comment]
Hi Kjetil, 

good point, thanks for the suggestion! Let me set a "new option" label for now, but we'd have to check whether this should be a new option to the "Align declarations" rule or rather a new cleanup rule. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Kjetil, 

thanks again for opening this! With the next release, the "Align declarations" rule will have this new option:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/607b4105-0d63-43f3-a919-3d8de26b8e76)

Example:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/043946e7-e8a8-410c-90b6-4b5a3bfd547e)

Existing one-liners are kept …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/96cb84da-3191-4679-8c18-b8588abf963e)

… unless they come with VALUEs:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/f2ea84c8-18d9-46b1-93ec-fbd154447b27)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Kjetil, 

thanks again for pointing this out – alignment of ENUMs should now work with version 1.13.0!

Kind regards,
Jörg-Michael
