### ISSUE TITLE
"Standardize empty lines within methods" deletes lines when applied but let them live in profile settings

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#195]
Hey,

I have a problem with the rule "_Standardize empty lines within methods_" deleting lines in code when the ABAP Cleaner runs - the same code behaves different when pasted in the configuration window.

Here is the code in the configuration window:

![CleanShot 2023-11-10 at 13 24 42](https://github.com/SAP/abap-cleaner/assets/3112128/57d53e13-fc91-4ed9-90d8-eceabc56d803)

I'd like to preserve the 2 empty lines (row-nr. 4 and 5) between DATA and the FREE-statement so I set the "_Max. empty lines within methods_"-parameter to 2.
It looks like the lines would be preserve BUT

![CleanShot 2023-11-10 at 13 25 42@2x](https://github.com/SAP/abap-cleaner/assets/3112128/4c0e3770-04bf-4c5c-8fed-0ef78660aae1)

as soon as I run the ABAP Cleaner one of the lines get deleted.

Could you please help me with this?

Thanks!

Regards,
Vlad

**Comment by jmgrassau** [comment]
Hi Vlad, 

that's a good point – this is done by the rule "Rearrange local declarations" (even if it has nothing to rearrange in this case). It would indeed be better if "Rearrange local declarations" observed the setting from "Standardize empty lines within methods"! 

Another issue is that if "Rearrange local declarations" changes something (even the number of line breaks), it should be displayed in the "Rule Used in Current Selection" list in the main window, which was not the case when I tried the scenario. 

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment]
Hi JM,

which parameter of "_Rearrange local declarations_" does this? 

Regards,
Vlad

**Comment by jmgrassau** [comment]
Hi Vlad, 

there is no parameter for this in "Rearrange local declarations" – but I now changed the rule to simply keep multiple empty lines if they are found in such cases, so this will be fixed with the next release.

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment]
Thanks JM!

**Comment by jmgrassau** [comment]
Hi Vlad, 

this should now be fixed with version 1.11.1, which was just released!

Kind regards,
Jörg-Michael
