### ISSUE TITLE
"Align assignments to the same object" doesn't seem to work

### ISSUE THREAD

**Issue by VladGhitulescu** [SAP/abap-cleaner#196]
Hey,

I would like to align the "=" sign in assignments just like in the example 

![CleanShot 2023-11-10 at 14 01 44@2x](https://github.com/SAP/abap-cleaner/assets/3112128/d68dd946-b52a-4ebf-a250-0e40cb3fd16e)

Within the pasted IF however it doesn't seem to work:

![CleanShot 2023-11-10 at 14 02 14@2x](https://github.com/SAP/abap-cleaner/assets/3112128/32a51299-bf2d-4196-8445-173f2b439b47)

The lines 4 and 5 are not aligned.

Any idea why?

Thanks!

Regards,
Vlad

**Comment by ConjuringCoffee** [comment]
The alignment is only done when the assignment is to the same object. Lines 4 and 5 assign a value to entirely different objects, so  they are not aligned.

**Comment by VladGhitulescu** [comment]
I understand. 

Is there any setting in the configuration in order to align the =s also for different objects?

**Comment by jmgrassau** [comment]
Hi Vlad, 

> Is there any setting in the configuration in order to align the =s also for different objects?

No, I'm not aware of such a setting – and it would go against the style guide rule 
[Align assignments to the same object, _but not to different ones_](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#align-assignments-to-the-same-object-but-not-to-different-ones)

Looking at your example, you would get:

```ABAP
lv_korr =                                      abap_true.
```

(if I counted the number of spaces correctly) and I doubt this would improve readability – maybe instead you could add a line break above the ```ls_adrc_chk_status_2_korr-...``` block? 

Generally, unless you select the "essential" profile, ABAP cleaner does in some cases go _beyond_ the style guide (automating things that are not explicitly demanded by the style guide), but we usually try to not go _against_ it – so I think I'd close this for now.

Kind regards,
Jörg-Michael

**Comment by VladGhitulescu** [comment]
Hi JM,

it makes sense.

Thanks, I learned something new! ;-)
