### ISSUE TITLE
##Needed is not correct recognized

### ISSUE THREAD

**Issue by fmabap** [SAP/abap-cleaner#200]
Hi, 
in the following example is ##NEEDED not at the end of the variable declaration.
ABAP-Cleaner set it to the end, but then it does not recognize that it is there and creates a TODO.
Can you please fix it?

<img width="1584" alt="image" src="https://github.com/SAP/abap-cleaner/assets/101019006/cda9dbb8-23b0-4d46-9f14-85a017ec5178">

```abap
 METHOD test.

    ##NEEDED data lv_msg type bapi_msg.

    DATA: lv_field TYPE c,
          ##NEEDED lv_msg2 type bapi_msg.

    MESSAGE e001(000) INTO lv_msg.
    MESSAGE e001(000) INTO lv_msg2.

    lv_field = 3.
    WRITE lv_field.
  ENDMETHOD.
```

Best regards
Frank

**Comment by fmabap** [comment]
Hi Jörg-Michael,
great thank you!

Best regards
Frank

**Comment by jmgrassau** [comment]
Hi Frank, 

thanks again for opening this issue – this is now fixed with version 1.11.2, which was just released!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi, 

sorry, I entered the wrong issue number in the above commit [enable ABAP cleaner menus for WebDynpro implementations](https://github.com/jmgrassau/abap-cleaner/commit/e25279abc797229588648bd816d71af7f174cafb) – this belongs to issue #220!

Kind regards,
Jörg-Michael

**Comment by fmabap** [comment]
Hi Jörg-Michael,

no problem. Thank you for fixing it. It works in my Testprogramm and also in the productive code.

Kind regards
Frank
