### ISSUE TITLE
Feature request: Use BAPI_TRANSACTION_COMMIT instead of COMMIT WORK statement

### ISSUE THREAD

**Issue by StefanRutzmoser** [SAP/abap-cleaner#201]
Hi @jmgrassau,

I want to request a new rule to replace the statements COMMIT WORK and ROLLBACK WORK with the function modules BAPI_TRANSACTION_COMMIT and BAPI_TRANSACTION_ROLLBACK.

This is because especially in ERP systems the mechanism of buffering data to be committed in function groups is a common use case. These function groups then provide a specific function module to refresh their buffer. These function modules are registered via BUFFER_SUBSCRIBE_FOR_REFRESH and finally called implicitly by BUFFER_REFRESH_ALL, which is called inside BAPI_TRANSACTION_COMMIT and BAPI_TRANSACTION_ROLLBACK. There are some if not many function groups that trust on this mechanism and expect that after a commit work the buffers are clean again.

**COMMIT WORK**
```
COMMIT WORK.
```

should be replaced by

```
CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'.
```

**COMMIT WORK AND WAIT**
```
COMMIT WORK AND WAIT.
```

should be replaced by

```
CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING wait = abap_true.
```

**ROLLBACK WORK**
```
ROLLBACK WORK.
```

should be replaced by

```
CALL FUNCTION 'BAPI_TRANSACTION_ROLLBACK'.
```

Regards,
Stefan

**Comment by ConjuringCoffee** [comment]
Hi Stefan, I'd like to point you to the [limitations section of the documentation](https://github.com/SAP/abap-cleaner#limitations-and-known-issues):

> ABAP cleaner strives to offer cleanup rules that automatically detect what can be improved in the given ABAP code, so after some initial configuration, users shall be able to apply "everything everywhere" with just one keystroke. ABAP cleaner is therefore restricted to cleanup rules that keep functionality unchanged and can be applied without any additional user interaction, or need for subsequent inspection of changes.

Your suggestion changes the behavior of the ABAP code, and therefore doesn't fit in with the approach of "fire and forget". I don't think ABAP Cleaner is the right place for it 😉 

Please also check the discussion here: https://github.com/SAP/abap-cleaner/issues/158#issuecomment-1774083190

**Comment by StefanRutzmoser** [comment]
Hi @ConjuringCoffee,

I see your point and therefore will close this.

But to have the requirements complete how to change the code (even if it needs to be done manually), I want to add this hint here:

One thing to look at is the SY-SUBRC after `COMMIT WORK AND WAIT`. In case the COMMIT WORK AND WAIT inside BAPI_TRANSACTION_COMMIT is other than 0, the function module sets an error message into its exporting parameter RETURN.
So if the SY-SUBRC is checked by the program, the code needs to be changed like this:

```
COMMIT WORK AND WAIT.
IF sy-subrc <> 0.
  " do_something
ENDIF.
```

should be replaced by

```
CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING wait   = abap_true
                                                  return = DATA(lt_return_of_commit).

IF lt_return_of_commit IS NOT INITIAL.
  " do_something
ENDIF.
```

**Comment by jmgrassau** [comment]
Hi Stefan and ConjuringCoffee, 

this is indeed out of scope for ABAP cleaner because of the limitation ConjuringCoffee mentioned, but nevertheless thanks for the idea and discussion! We'd rather have one idea too many than missing one! 

Kind regards,
Jörg-Michael
