### ISSUE TITLE
"Align parameters and components" doesn't work if a method call is on the same line as a `WHEN` or `IF` condition

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#207]
Hi Jörg-Michael, the second method parameter in the following example isn't indented correctly:

```abap
    DATA example TYPE string.

    CASE example.
      WHEN 'when'. call_example( i_1 = 1
               i_2 = 2 ).
    ENDCASE.
```

I know that this style contradicts the Clean ABAP rule "No more than one statement per line", but I still think that the ABAP Cleaner should support this case correctly. 😉

**Comment by ConjuringCoffee** [comment]
It also seems to be the case for `IF` conditions:

```abap
    IF example = 'when'. call_example( i_1 = 1
               i_2 = 2 ).
    ENDIF.
```

**Comment by ConjuringCoffee** [comment]
After a discussion internally, we concluded that it is best to move the method call to a separate line. This problem is therefore obsolete.

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee,

that's nevertheless a nice finding – will be fixed with the next release!

Kind regards,
Jörg-Michael
