### ISSUE TITLE
Settings are currently independent of Eclipse workspace

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#211]
Hi Jörg-Michael, I set up a new Eclipse today. After I installed the ABAP Cleaner, I noticed that my ABAP Cleaner settings were already there.

This hasn't caused any issues for me yet, but it isn't really consistent with other plugins (like ADT).

I imagine this could be problematic for developers working for multiple companies on the same machine. I imagine they use different Eclipse installations and / or different workspaces for the different companies. They'd always have to make sure to switch their current profile, even if they are using separate workspaces.

**Comment by ConjuringCoffee** [comment]
Also, if someone transfers only their Eclipse installation and workspace to another client, they lose their ABAP Cleaner settings.

They'd have to transfer their data from `AppData\Roaming\SAP\ABAP cleaner` additionally.

**Comment by ConjuringCoffee** [comment]
Hi Jörg-Michael, that sounds good to me. Thank you!

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

thanks for your feedback and for this idea – version 1.16.0 will now use workspace-specific cleanup settings!

Kind regards,
Jörg-Michael
