### ISSUE TITLE
SQL examples for rule "Align logical expressions"

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#215]
Hi Jörg-Michael, you added additional options for SQL statements in the latest update. Thanks again for that! Unfortunately, the current examples don't cover them yet. It would be great if you could include some for them too - thanks! 🙂

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

good point, will do!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

with the added examples, the "Align logical expressions" just about fits on my 4K screen… but now you can watch the effect of the new options for "SQL: Align … with ON / WHERE / HAVING / WHEN", too:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/6977854f-e3d3-41e2-8c90-40b833113538)

Kind regards,
Jörg-Michael
