### ISSUE TITLE
Reasoning behind default values of SQL options in "Align logical expressions"?

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#216]
Hi Jörg-Michael, I'd like to understand your reasoning behind the default values of the new SQL options in rule "Align logical expressions". Why didn't you choose the same settings as for the other keywords? What makes the SELECT special here?

![image](https://github.com/SAP/abap-cleaner/assets/72548231/551a75a5-350b-4f3f-a950-a849bfb632c5)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

as in #214, the reason for the current defaults is that I found so many examples in real-life code where developers chose this layout, particularly for 

```ABAP
    WHERE col1 = 'a'
      AND col2 = 'b'
      AND col3 = 'c'
      AND col4 = 'd'
```

while there is this odd gap (which I assume is the main reason for the discussion in #97) if you use: 

```ABAP
    WHERE     col1 = 'a'
          AND col2 = 'b'
          AND col3 = 'c'
          AND col4 = 'd'
```

Personally, I indeed like left-align for "IF" and right-align for the longer keywords (ELSEIF, CHECK, WHILE, WHERE, UNTIL) to close that gap, but I couldn't base that on so many samples as with WHERE. But I realize the inconsistency, of course. 

Which (default) settings would you prefer? 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Your explanation makes sense to me: It matches what people are used to. I'll try running with the default settings for the SQL options for a while and see how it feels. Thanks!
