### ISSUE TITLE
ABAP Cleaner bug with chained CATCH statement

### ISSUE THREAD

**Issue by Finbar-Callaghan** [SAP/abap-cleaner#223]
Hello,
Hopefully this issue helps more than my last attempt...
First step establish my version
![image](https://github.com/SAP/abap-cleaner/assets/141810374/3b4dfbe6-2493-4f3d-a094-41120ed2f535)
In essence this is the crux of the matter…
So the following CATCH statements work fine, 
    TRY.
        my_struct = cl_abap_structdescr=>create( comp_tab ).
        my_table  = cl_abap_tabledescr=>create( p_line_type = my_struct ).
      CATCH cx_sy_struct_creation.
      CATCH cx_sy_table_creation.
    ENDTRY.

However, when the CATCH statement is chained on multiple lines in the following manner it fails,
    TRY.
        my_struct = cl_abap_structdescr=>create( comp_tab ).
        my_table  = cl_abap_tabledescr=>create( p_line_type = my_struct ).
       CATCH : cx_sy_struct_creation,
               cx_sy_table_creation.
    ENDTRY.

It error’s with the following message.
![image](https://github.com/SAP/abap-cleaner/assets/141810374/7a928411-79c5-4108-9ba2-1acf1273ae8f)

And when the code is flipped to distinct catch statements;
<img width="482" alt="image" src="https://github.com/SAP/abap-cleaner/assets/141810374/ebe0b1ed-8617-4499-98c0-e215260c7f3f">
Then ABAP Cleaner runs successfully
![image](https://github.com/SAP/abap-cleaner/assets/141810374/955738e8-c26b-4f11-b296-71c96034a7e8)
Once again keep up the good work!

Regards,
Finbar

PS Have a Merry Christmas and a Happy New Year...

**Comment by ConjuringCoffee** [comment]
I think the error message is quite clear though, right? 😉 Chained `CATCH` statements aren't supported and you need to refactor the code first. I reckon, this is simply out of scope.

Chained `CATCH` statements are really bad practice anyway...

This:
```abap
TRY.
    logic( ).
  CATCH: cx_exception_1, cx_exception_2.
    handle_error( ).
ENDTRY.
```

Resolves to this:

```abap
TRY.
    logic( ).
  CATCH cx_exception_1.
  CATCH cx_exception_2.
    handle_error( ).
ENDTRY.
```

**Comment by Finbar-Callaghan** [comment]
Confession time, yes I’ve picked up some bad habits.

However, this is what I want from ABAP Cleaner, to highlight, areas of my code I can improve and to make me a better coder. To be honest, like most developers, I’ve been focused on UI5, Javascript, UI5 Tooling, VS Code, CDS, RAP, Docker etc and my ABAP has been a bit neglected of late. Hence, working on ABAP in the Cloud to understand it’s limitations using ABAP Cleaner is just what I needed.

Therefore, can I respectfully suggest as this is not a flaw with ABAP Cleaner and it’s due to underlying principles that ABAP Cleaner will not process a chain of CATCH commands, because it’s not best practice. Potentially amending the message to something similar to 

“Chain of CATCH commands cannot be processed by ABAP Cleaner, as it is not best practice.”

Anyway I want to thank you for taking the time do you such a detailed and helpful response to my question, greatly appreciated and I’ll set the status to Close issue.

All the best…
Finbar
