### ISSUE TITLE
"Install new Software" not available

### ISSUE THREAD

**Issue by I034943** [SAP/abap-cleaner#235]
![image](https://github.com/SAP/abap-cleaner/assets/53301188/52903338-72c1-4b41-81dc-edd83f7b0f64)

I'm not able to add the ABAP Cleaner due to this

**Comment by I034943** [comment]
Issue resolved

**Comment by jmgrassau** [comment]
Hi, 

thanks for opening this issue – this will be added to the ["Known Installation Issues"](https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md) page with the next release! 

Kind regards,
Jörg-Michael
