### ISSUE TITLE
Feature Request: Comparing different Profiles

### ISSUE THREAD

**Issue by bastianStr** [SAP/abap-cleaner#239]
It would be great to have an possibility to compare differents profiles to see differences between the options. 

And it would be nice if we can create a new "default" profile with all the default flags set.

**Comment by ConjuringCoffee** [comment]
You can already compare profiles using the "Highlight" functionality on the "Profiles and Rules" screen:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/12d7fcbb-6827-426a-8af9-20f9cda4a1e1)

![image](https://github.com/SAP/abap-cleaner/assets/72548231/cc31ae3b-7701-4b37-b7f7-4f13ab720401)

Does this do what you want? 😉

**Comment by jmgrassau** [comment]
Hi bastianStr, 

an alternative approach (fewer clicks, but much more technical) would be to use ABAP cleaner menu "Help / Open Profiles Folder", then open two of the profile e.g. in Notepad++ (those are JSON-like files with the extension .cfj), and use the Compare plug-in: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/7667df8a-be1d-496e-924c-a1a7931e8767)

Probably you can guess at least in most cases which rules and options are meant :-)

> And it would be nice if we can create a new "default" profile with all the default flags set.

If you go to the "Profiles and Rules" editor and in section "Profiles" click "**Create**", the newly created profile will start with the _default_ settings regarding both rule activation and configuration (while with the button "**Copy**", they start with the settings of whatever profile that was selected when you hit "Copy"). 

Alternatively, at the bottom left of the window, you can press "**Activate: Default**" or "**Activate: Essential**" to activate the default / essential rules in the currently selected profile and deactivate all others (note that these buttons only change rule _activation_, but not rule _configuration_). When ABAP cleaner is installed, the "default" and "essential" profile only differ in rule activation, while the detailed configuration options are the same (but you can change these profiles as you like, of course). 

Whatever you do after opening the window will be persisted when you leave the window with "Save Profiles and Exit", or discarded with "Cancel". 

Not sure whether this answers your question or whether you meant it in a different way? 

Kind regards,
Jörg-Michael
