### ISSUE TITLE
SELECT FOR: Unexpected term

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#241]
Image the following source code within a class method:
```
SELECT SINGLE FOR UPDATE * FROM /scwm/mfscch
  INTO ls_mfscch
  WHERE lgnum   = ls_mfscch-lgnum
    AND plc     = ls_mfscch-plc
    AND channel = ls_mfscch-channel.
```

ABAP Cleaner throws an error on execution:
![image](https://github.com/SAP/abap-cleaner/assets/99023738/75788d7b-4687-43e2-91f1-a32ceb8ef071)

**Workaround:**
Comment the related sql statement, then execute ABAP Cleaner and uncomment the statement again.

**Comment by jmgrassau** [comment]
Hi Marius,

thanks again for reporting this – this should now work with version 1.13.1, which was just released!

Kind regards,
Jörg-Michael

**Comment by mraht** [comment]
Yes, works now - many thanks! 👍🏼
