### ISSUE TITLE
Wrong comment "never used"

### ISSUE THREAD

**Issue by owelzel** [SAP/abap-cleaner#243]
In the following code the comment "never used" for variable timezone is wrong.

`  METHOD something.`
`    DATA date     TYPE d.`
`    DATA time     TYPE t.`
`    DATA datetime TYPE timestamp.`
` `
`    " TODO: variable is assigned but never used (ABAP cleaner)`
`    SELECT SINGLE tzonesys FROM ttzcu INTO @DATA(timezone).`
`    CONVERT DATE date TIME time INTO TIME STAMP datetime TIME ZONE timezone.`
` `
`    WRITE datetime.`
`  ENDMETHOD.`

**Comment by jmgrassau** [comment]
Hi owelzel, 

ah, well spotted! I must have been confused by TIME ZONE being on the right-hand side of INTO. This will be fixed with the next release.

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
P.S.: menu View / Highlight Write Positions now correctly shows ```timezone``` in black in the CONVERT statement:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/e7fa9e37-3d73-4a89-ab5e-2feebf15f8b3)

**Comment by jmgrassau** [comment]
Hi owelzel,

thanks again – this error should now be fixed with version 1.13.1, which was just released!

Kind regards,
Jörg-Michael

**Comment by owelzel** [comment]
Hi Jörg-Michael,

I did a successful retest with 1.13.1.
Thanks for your quick reaction!

Best regards
Oliver
