### ISSUE TITLE
Comments in AMDP code

### ISSUE THREAD

**Issue by owelzel** [SAP/abap-cleaner#244]
AMDP methods should not be considered for "never used" comments.
The analysis is not correct and the usage of " to start a comment even leads to a syntax error in AMDP methods.

 `   METHODS something_amdp`
`      IMPORTING VALUE(param) TYPE i.`
...
`  METHOD something_amdp BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT.`
`    " TODO: parameter PARAM is never used (ABAP cleaner)`
` `
`    DECLARE query STRING;`
`    query = 'text' || param;`
`  ENDMETHOD.`

**Comment by jmgrassau** [comment]
Hi owelzel, 

thanks a lot for reporting this, this bug will be fixed with the next release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi owelzel,

thanks again for this bug report – this issue should now be fixed with version 1.13.1, which was just released!

Kind regards,
Jörg-Michael

**Comment by owelzel** [comment]
Hi Jörg-Michael,

I did a successful retest with 1.13.1.
Thanks for your quick reaction!

Best regards
Oliver
