### ISSUE TITLE
Feature request: Indicate "before" and "after" in code comparison view

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#249]
Hi Jörg-Michael, I have a low-priority usability request for you regarding the code comparison view: Would it be possible to indicate which code is "before" and which is "after" view? It isn't always immediately obvious which is which. 

Something similar to this would be nice:
![image](https://github.com/SAP/abap-cleaner/assets/72548231/3f6a3a91-62b8-4bdf-b6bf-c9df23e0deb2)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

yes, I get the point, esp. because comparison of different source code versions in ADT can have the reverse order. This would of course be a bit at the expense of the code display height. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee and @MichiFr,

I now added these labels: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/70df7735-852c-4118-a60e-15d552aa561b)

To add some extra value to the space they use up, the "After cleanup" label shows some statistics on the main window (but not on the Profiles window, where they make little sense): 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/67cd0636-97a3-4e51-830b-16201b06d959)

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Thanks!

**Comment by MichiFr** [comment]
Yes, looks good for me, too! Both captions and the additional comment.

Thanks again!

**Comment by MichiFr** [comment]
Updated -> Looks smart ;-)
![image](https://github.com/SAP/abap-cleaner/assets/28045390/9100c7cd-3300-4eda-9a74-ebc39fe707d3)

Thanks!

**Comment by jmgrassau** [comment]
Hi Michael, 

perfect, thanks for the feedback!

Kind regards,
Jörg-Michael
