### ISSUE TITLE
Variable names to lower case

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#252]
It would be great if ABAP Cleaner would be able to set variable names to lower case.

Sometimes the developer writes something like this: `DATA(lv_an_eXamPLe) = ...`
ABAP of course only allows lower case-names. Currently you have to run pretty printer to fix this.

**Comment by jmgrassau** [comment]
Hi Marius,

the cleanup rule "Convert upper and lower case" has the option "Keep camel case identifiers", which is active by default and prevents ABAP cleaner from removing camel case. If you deactivate this option, you would indeed get ```DATA(lv_an_example)```. However, this would also put CDS View names and fields to lower case – and with those, readability sometimes benefits quite a bit from camel case. 

Hm, maybe we'd need some more fine tuning here, e.g. different settings for ABAP identifiers (local variables, attributes etc.) versus VDM identifiers? Not sure, though, if that can easily be implemented. 

In the naming conventions that I am familiar with, it would even be sufficient to say: "put every identifier to lower case which contains an underscore and does NOT start with I_, P_ or C_" (but so far, ABAP cleaner does not rely on specific naming conventions). 

Kind regards,
Jörg-Michael

**Comment by mraht** [comment]
Hi Jörg,

must have overlooked that option - thanks for pointing that out! :)

From my perspective naming conventions shouldn't be considered as they're changing regulary over time, every customer/developer, system and so on have their own and additionally SAP now recommends getting rid of all encodings (https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#avoid-encodings-esp-hungarian-notation-and-prefixes). One would have to end up with a solution that is customizable by the developer/user of abap cleaner.

Maybe the development object type could be used instead to determine whether lower-case, mixed or upper-case should be used? In any case the user is able to create a new ABAP Cleaner check profile with activated or deactivated "Keep camel case identifiers"-flag.

Thus I'm quiet happy now with the option you pointed out and will create a new profile with deactivated flag for e.g. CDS. Many thanks! :)
