### ISSUE TITLE
No alignment of comparison operators in case of variable names with underscore

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#255]
ABAP Cleaner doesn't align comparison operators (EQ and LT in the following example) in a SELECT if a variable name mentioned in the SELECT consists of at least 3 underscores (structure + attribute name, e.g. `ls_test-struct_test` would be ok, but `ls_test-str_uct_test` wouldn't be):

```
TYPES: BEGIN OF s_test,
         search_tst TYPE abap_bool,
       END OF s_test.

DATA(ls_search_tst) = VALUE s_test( search_tst = abap_false ).

SELECT FROM sflight
  FIELDS *
  WHERE carrid EQ 'AA'
    AND (    connid                    EQ '0123'
          OR price LT 10
          OR @ls_search_tst-search_tst EQ @abap_false )
  INTO TABLE @DATA(lt_result).
```

**Comment by mraht** [comment]
Also the case with if - in this case the third check prevents the alignment of the first IS NOT INITIAL:
```
CHECK data_ref IS NOT INITIAL
  AND data_ref_type                 IS NOT INITIAL
  AND has_valid_data_ref( )-success EQ abap_true.
```

**Comment by jmgrassau** [comment]
Hi Marius, 

this is not a bug, it's a feature ;-) It is caused in cleanup rule "Align logical expressions" by the option "Do not align if more than [20] inner spaces would be required", which tries to avoid awkwardly large gaps in the code. If you set this to 22 or more, things will look as you expected in these examples: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/71e33381-41a8-41c2-bf64-b1131e5f0b6c)

Kind regards,
Jörg-Michael

**Comment by mraht** [comment]
Hi Jörg, ok, great - thanks for the fast answers and continous work on this great tool! Keep it up :)
