### ISSUE TITLE
Align consecutive attributes and variables

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#268]
It would be nice if abap-cleaner would also align consecutive value assignments attributes of a class. In this case abap-cleaner would align the following value assignments...
```
METHOD constructor.

    rul_id = iv_rul_id.
    par_id = iv_par_id.
    type = iv_type.
    data_type = iv_data_type.
    ui_type = iv_ui_type.
    sort_nr = iv_sort_nr.
    instance = me.

    " ...like this
    rul_id    = iv_rul_id.
    par_id    = iv_par_id.
    type      = iv_type.
    data_type = iv_data_type.
    ui_type   = iv_ui_type.
    sort_nr   = iv_sort_nr.
    instance  = me.

 ENDMETHOD.
```

Also normal variables following directly after another could be aligned together:
```
    DATA(ls_cnf_par) = map_int_to_ext( ).
    DATA(ls_cnf_par_new) = io_cnf_par->as_structure( ).

    " vs.
    DATA(ls_cnf_par)     = map_int_to_ext( ).
    DATA(ls_cnf_par_new) = io_cnf_par->as_structure( ).

```

Of course, abap-cleaner doesn't know whether these variables belong to eachother or not. Thus it should be a separate setting to be able to turn off or on.

**Comment by ConjuringCoffee** [comment]
This topic is already being discussed in: #234

**Comment by mraht** [comment]
..closing in favour of #234
