### ISSUE TITLE
Installation error with Eclipse Version: 2023-12 (4.30.0)

### ISSUE THREAD

**Issue by gurmukha** [SAP/abap-cleaner#269]
Getting error while installing ABAP clearner in Eclipse Version: 2023-12 (4.30.0) :

Unable to read repository at https://sap.github.io/abap-cleaner/updatesite/content.xml.
Unable to read repository at https://sap.github.io/abap-cleaner/updatesite/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by jmgrassau** [comment]
Hi gurmukha, 

this sounds like one of the [Known Installation Issues](https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md) – does the solution work on your system?

Kind regards,
Jörg-Michael

**Comment by gurmukha** [comment]
Yes, thanks a lot it resolve the issue - I did maintain this earlier but it was older folder of older eclipse version which was my mistake and now i pointed to correct file.
Solution: Open the file eclipse.ini from your Eclipse installation path. Right after the line -vmargs, add the following two lines:

-Djavax.net.ssl.trustStore=NONE
-Djavax.net.ssl.trustStoreType=Windows-ROOT
Now save eclipse.ini, restart Eclipse and try menu 'Help / Install New Software' again.

**Comment by jmgrassau** [comment]
HI gurmukha, 

perfect, then I hope you will enjoy using ABAP cleaner!

Kind regards,
Jörg-Michael
