### ISSUE TITLE
Feature request: Option to replace =,<,>,<=,>=,<> by EQ, LT, GT, LE, GE, NE

### ISSUE THREAD

**Issue by mraht** [SAP/abap-cleaner#273]
Currently there’s a rule replacing `EQ, LT, GT, LE, GE, NE` with `=,<,>,<=,>=,<>`. I'd like to have the reversed option, as I prefer the character-based comparison. 

I know, a widely discussed topic, but SAP docu and clean abap just enforce the consistent use not the usage of either version.

**Comment by jmgrassau** [comment]
Hi Marius, 

hm, yes, personally, I don't find ```EQ, LT, GT``` to be better readable at all (except maybe for the distinction between ```=``` as an assignment operator and ```EQ``` as a comparison operator, for which other programming languages have ```==```); but as far as I know, there is indeed only the recommendation by the [ABAP Keyword Documentation](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abenlogexp_any_operand.htm) to be consistent by using either one or the other set of operators. 

So it shouldn't be too difficult to add an option to enable either direction (and rename the rule "Prefer =, <>, <= etc. to EQ, NE, LE etc." accordingly). I guess you'd just want to align this setting with your team to avoid edit wars…

Kind regards,
Jörg-Michael

**Comment by mraht** [comment]
Hi @jmgrassau,

> I don't find EQ, LT, GT to be better readable at all (except maybe for the distinction between = as an assignment operator and EQ as a comparison operator, for which other programming languages have ==)

Yes, the '=' instead of '==' leads IMHO to some disadvantages (s. https://github.com/SAP/styleguides/issues/282#issuecomment-1719689088) and that's why I prefer the character-based comparison it's more consistent from my point of view.

> So it shouldn't be too difficult to add an option to enable either direction

Great to hear that. :)

> I guess you'd just want to align this setting with your team to avoid edit wars…

Yes, but I think that's the case with some other settings, too. Also we use the folders option to align the settings with eachother - very great feature! :)

I love the work you've already done so far for abap cleaner very much - keep it up! :)

**Comment by jmgrassau** [comment]
Hi Marius, 

with the next release, the cleanup rule "Prefer =, <>, <= etc. to EQ, NE, LE etc." will be renamed to "Use consistent set of comparison operators" and allow to specify the preferred set of operators:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/2b3600c4-76e8-4933-b97a-f7b8e54dbf26)

With the "textual" setting, you get:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/6fe66027-af95-4e97-acea-6bb52ff8ebee)

Kind regards,
Jörg-Michael

**Comment by mraht** [comment]
Many thanks! :)

**Comment by jmgrassau** [comment]
Hi Marius, 

thanks again for this idea – the new option is now included in version 1.16.0, which was just released!

Kind regards,
Jörg-Michael
