### ISSUE TITLE
Suggestion or Feedback : allow running ABAP cleaner from reviewer point of view 

### ISSUE THREAD

**Issue by gurmukha** [SAP/abap-cleaner#274]
Dear Team,

My suggestion to allow running ABAP cleaner if we want to review the code without making any changes in the display mode.

I am not able to use the ABAP Cleaner in interactive mode as it is locked by some other user in the transport so cannot run the tool to check if there are any improvements like spelling mistakes or negation conditions used or any identation.

Please provide your views if it is possible or there is any other option to execute the tool to display the changes in the display mode even if the object is locked under some transport.

Thanks for the valuable tool which helps to improve coding.

Regards,
Gurmukh Singh

**Comment by ConjuringCoffee** [comment]
Hi Gurmukh, you can simply use the read-only preview to do this:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/25e629c3-9344-4e46-bfee-fbf7ad11f720)

**Comment by jmgrassau** [comment]
Hi Gurmukh Singh, 

I guess the menu "Show Read-Only Preview" menu that ConjuringCoffee pointed out is exactly what you looked for – it was indeed originally proposed in #114 for the purpose of code reviews. Really a great idea, I'm also using it all the time! So I think I can close this issue. 

Kind regards,
Jörg-Michael
