### ISSUE TITLE
Feature request: Downgrade to older syntax

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#284]
Hi Jörg-Michael, here's an unusual request: I'd like to be able to automatically downgrade from newer syntax to older syntax. For me, my main use case would be for open-source developments: Some of the largest open-source repositories still support older releases. For example, abapGit supports 7.02 or code-pal supports 7.40. Personally, I am repeatedly running into the problem of accidentally using newer syntax that isn't supported by the project.

Of course this isn't always possible, but I think it would make working for these older releases easier.

Here's an example I encountered today. Before:
```abap
DATA(li_root_as_element) = CAST if_ixml_element( mi_root ).
```

Expected result to support 7.02:

```abap
DATA li_root_as_element TYPE REF TO if_ixml_element.
li_root_as_element ?= mi_root.
```

**Comment by fabianlupa** [comment]
Just fyi, abaplint supports automatic downporting to exactly 7.02 and can also tell you in your development flow what syntax elements aren't available in your target release.

**Comment by ConjuringCoffee** [comment]
I should really stop procrastinating setting up abapLint, huh? 😳 

Judging by the thumbs-up from Jörg-Michael, it seems unlikely this will be added to the ABAP Cleaner. I am therefore closing this issue.

**Comment by larshp** [comment]
@ConjuringCoffee I am available if you'd like an intro or help doing some initial setup

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

yes, I think this is a bit out of scope for ABAP cleaner, but it's great that abaplint already supports this. Thanks a lot, @larshp, for offering your help!

Kind regards,
Jörg-Michael
