### ISSUE TITLE
Unused Varables TODO for message

### ISSUE THREAD

**Issue by TheSaan** [SAP/abap-cleaner#285]
When writing a message statement, even though all "TODO" commenting functions are disabled, the statement is still added for the "INTO DATA(lv_msg)." variable in case it's not used for further messages. 

There must be an option to not write the todo statement for messages

**Comment by jmgrassau** [comment]
Hi TheSaan, 

do I understand you correctly that you configured the "Delete unused variables" rule with 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/af3355fa-63a9-4c5c-9c99-24764c15c6ad)

but ABAP cleaner nevertheless inserts a TODO comment above the MESSAGE … INTO DATA(…) statement? That's odd and I can't reproduce it – can you provide an example code? 

In the special case of MESSAGE … INTO DATA(…), you should get the following warning, which also shows that the issue can be resolved with a ##NEEDED pragma:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/fd60a8df-1dda-40fa-9ead-53bd95179ae4)

This pragma also satisfies the SLIN warning for Field Attributes:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/bd62bf43-018a-494a-84e7-78ddf165a65e)

I think ABAP cleaner should offer an option to automatically insert the ##NEEDED pragma in this special (but frequent) case, so let me put the label "new option" to this issue! 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Related to the new option: https://github.com/SAP/abap-cleaner/issues/275

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

ah, you're right, thanks! Then we don't need "new option" here, because it would be a duplicate. Okay, let's see if TheSaan found a bug where the TODO is inserted although it is deactivated. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi TheSaan, 

now that's what I call a screenshot! ;-)

However, this is really odd, because even with your exact sample code, I don't get this behavior with these settings. The TODO comment is not added … 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/0bd36172-27fc-4521-92ed-9728393a9fc7)

… and if it exists, it is even automatically removed:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/ca64f5e0-c0cf-4318-a02c-d44c42432a89)

Are you getting this with the current version 1.15.0 of ABAP cleaner? 

Kind regards,
Jörg-Michael

P.S.: Yes, the rule only works for local variables in METHOD, FORM, etc., not for the global ones on REPORT level.

**Comment by TheSaan** [comment]
I was using **1.12** for the test.

Now i upgraded the Version to **1.15**
![image](https://github.com/SAP/abap-cleaner/assets/11058501/abb905a9-ed8b-4e28-a28b-b713a690bfeb)

With the newer version it is working great. Sorry for the stupid problem of having simply and deprecated version running. 
The problem was, that i actually had the version on 1.15 before. But the customer runs a RDC environment where they recover a certain state every few days. 
And in that recovery the update is not available -.- 

**Thanks for this great tool!**

**Comment by jmgrassau** [comment]
Hi TheSaan,

ah, perfect, then that explains it! 

Does this "recovery" on the customer system mean that you could still install newer versions of ABAP cleaner there, but you'd have to do that over and over again? That's annoying, of course… 

Kind regards,
Jörg-Michael
