### ISSUE TITLE
Feature Request: Settings Option - Automatic Source Code Formatting on Save

### ISSUE THREAD

**Issue by Inn2-AMA** [SAP/abap-cleaner#296]
Hi Jörg-Michael, would it be possible to add a settings option "Automatic Source Code Formatting on Save".  So every time we save code in Eclipse, the ABAP Cleaner gets triggered?

**Comment by ConjuringCoffee** [comment]
This was already requested (by me 🙃), but unfortunately "there iscurrently no technical way for ABAP cleaner to hook into the save process".

See: #3
