### ISSUE TITLE
Shorter field names are not aligned in WHERE conditions

### ISSUE THREAD

**Issue by b4loghpeter** [SAP/abap-cleaner#299]
Dear Community,

We noticed that the automatic alignment option in the abapCleaner does not align some of our parameters with the other parameters. This applies to WHERE conditions in LOOPs, internal table operations (e.g. READ, DELETE), SQL statements, so basically everywhere. 

Example code:
```abap
DATA: lt_processed TYPE if_vch_rap_cp_types=>tt_procedure_assgmt.
LOOP AT lt_processed ASSIGNING FIELD-SYMBOL(<ls_processed>)
     WHERE     varconfigurationprofilename   = 'profile'
           AND changenumber                  = 'changenumber'
           AND objdpnprocessingsequencevalue = 1
           AND product = 'product'
           AND objectdependencyname          = 'dependency'
           AND isdeleted = abap_true
           AND validityenddate               = '20240101'
           AND validitystartdate             = '20250101'.
  EXIT.
ENDLOOP.
```

We would expect the alignment of the `= <value>` to be consistent also in the `product` and `isdeleted`  parameters. 

Could you please look into this?

Thanks & regards,
Peter

**Comment by ConjuringCoffee** [comment]
Hello Peter, the rule "Align logical expressions" has a setting that can influence this behavior:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/76deff7f-1208-40e4-997e-40003bc740f2)

I suspect that your limit is reached for these shorter component names.

**Comment by b4loghpeter** [comment]
Ah, you are absolutely right! Thanks a lot, I swear I was browsing through the settings for a good hour, but I missed this one at the bottom. It works fine now!
