### ISSUE TITLE
Bug: Variable use in CONVERT DATE ... TIME ZONE <here> not recognized

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#300]
Hello,
I got the ABAL Cleaner comment

```
    SELECT SINGLE tzonesys FROM ttzcu
      " TODO: variable is assigned but never used (ABAP cleaner)
      INTO @DATA(system_timezone).
```

even though the variable is used in the following:

`    CONVERT DATE i_date TIME i_hour INTO TIME STAMP DATA(begin) TIME ZONE system_timezone.
`
Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

thanks for opening this issue! I don't get this bug with the current ABAP release 1.16.0, could you check whether you have the current version? As far as I can see, this was already reported in #243 and should have been fixed with version 1.13.1.

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Yes, now it is fixed, thanks (and sorry for opening a duplicate issue).

By the way, I was wondering where to find the version info of ABAPCleaner. Maybe it can be displayed in the configuration Profiles/Rules window.

**Comment by ConjuringCoffee** [comment]
You can see the version number of any Eclipse add-on here: 

"Help" in the menu bar --> "About Eclipse IDE" --> "Installation Details"

![image](https://github.com/SAP/abap-cleaner/assets/72548231/334e5954-fa4f-4853-93a8-302367a2153c)

**Comment by jmgrassau** [comment]
Hi Edo, 

in addition to the info inside Eclipse (as mentioned above by ConjuringCoffee), you can use the menu "Help / About" from the ABAP cleaner main window; this works both in the plug-in and the standalone version: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/9bc0d3e4-7a40-4b92-9451-ec938971f6e2)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/ef94f1fc-209f-469f-acbf-cf45f01fc4a6)

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Ha, I never noticed that menu on the main screen before - thanks!

Thanks also to @ConjuringCoffee : To find out the ADT version, I always used the little icons on the "About" screen, and was always irritated because this shows a long list of sub-components.
