### ISSUE TITLE
Feature Request: No line between DATA declaration of a table and initialization

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#303]
Hi,
to loop over a list of "options", I want to create a "quasi-constant" table containing these constants.
I think there is no way in ABAP other than to do it like this:

```
  METHOD get_confirmed_quantity.
    DATA conf_cats TYPE STANDARD TABLE OF zb_c_purgdocsupplierconfirmati-SupplierConfirmationCategory WITH EMPTY KEY.

    conf_cats = VALUE #( ( 'AB' ) ( 'LA' ) ). " sometime there is just Lieferavis without Order Confirmation

    LOOP AT conf_cats INTO DATA(conf_cat).
```

However, ABAPCleaner then separates the DATA and its initialization, which I would prefer it not to do in this special case.
(I know, this is a very small detail, still I wanted to share this.)
Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

currently, I'd rather label this "no defect", because the idea behind this empty line – to separate upfront declarations from executable statements – is still valid here, isn't it? 

If you prefer an inline declaration, you could alternatively define a table type first (maybe even on class or global level is this table type could be useful in different places?) and then use it as the type of the VALUE constructor:

```ABAP
  METHOD get_confirmed_quantity.
    TYPES ty_tt_sup_conf_cat TYPE STANDARD TABLE OF zb_c_purgdocsupplierconfirmati-SupplierConfirmationCategory WITH EMPTY KEY.

    DATA(conf_cats) = VALUE ty_tt_sup_conf_cat( ( 'AB' ) ( 'LA' ) ). 

    LOOP AT conf_cats INTO DATA(conf_cat).
```

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Hi Jörg-Michael,

maybe we misunderstood each other?
I want to use the variable as a _constant_ (semantically). _Technically_ however, ABAP does not offer a syntax for this (only for simple variables, not for tables).

Because it is semantically a "declaration of a constant" I do not like to have the separation line in the middle of it.
The question is whether ABAPCleaner can detect such a "pseudo-constant" (a table which is immediately initialized) and suppress the line separation at this position.

Again, I am aware it is a very tiny detail (not a defect at all), but I wanted to let you know that this use case exists.

Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

ah, yes, now I understand your point! But then a number of questions come to mind:

* What if the VALUE statement used an importing variable in some place – ```VALUE ty_tt_any( ( 'A' ) ( 'B' ) ( iv_any ) ( iv_other ) )``` – then it wouldn't be a "pseudo-constant" anymore, right? 
* What if the VALUE statement used a constant, possibly in the form of cl_any_inferface=>co_any_constant? – I guess you could still consider it a "pseudo-constant", but ABAP cleaner couldn't determine whether the identifier really represents a constant. 
* What if multiple tables of this kind were initialized, would it be better to have the four lines as "declaration 1 – initialization 1 – declaration 2 – initialization 2", or rather "declaration 1 – declaration 2 – initialization 1 – initialization 2"? 

So, my feeling is that this is really rather a limitation of the ABAP language… just as you said, there is no technical equivalent for this (very valid) semantic scenario, and I assume that the initialization is indeed performed at runtime each time the method is called (not at compile time into a static storage). 

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Hi Jörg-Michael,
I think you are right. This cannot be easily overcome by ABAP Cleaner.
Best regards,
Edo
