### ISSUE TITLE
Bug: declaring a variable followed by "clean" deletes the variable

### ISSUE THREAD

**Issue by matthewdjb** [SAP/abap-cleaner#308]
In a method, I declare a new variable. Without saving I ctrl-4 and my new variable disappears.

So, before:
`METHOD mymethod.
   DATA mydata TYPE i.
ENDMETHOD.`

Ctrl-4, and after:
`METHOD mymethod.
ENDMETHOD.`

**Comment by ConjuringCoffee** [comment]
It sounds like you have the rule "Delete unused variables" to be configured to automatically delete unused local variables.

![image](https://github.com/SAP/abap-cleaner/assets/72548231/6cfa64cc-9a89-4c2d-b4dc-a5d595b46ba3)

For the reason you described, I prefer setting this to "add TODO comment" instead.

**Comment by matthewdjb** [comment]
That'll be nice. Thanks.

**Comment by ConjuringCoffee** [comment]
I'm not sure I got my point across correctly... You need to check your profile settings and change it yourself (if that is indeed the issue). 😉

**Comment by jmgrassau** [comment]
Hi Matthew and ConjuringCoffee, 

thanks for the discussion – I guess I can close this then?

Actually, my code writing practice has changed, too: When I need a new variable for something, I write both the declaration and the first assignment to whatever place I am in the code. Then I press Ctrl+4 to let the cleanup rule "Rearrange local declarations" move the declaration to its suitable place (unless it's an inline declaration, of course). 

I've suffered this disappearing of a freshly written declaration a couple of times, too, but this has kind of educated me to right away use a new variable – which I prefer to the "danger" of ending up with undetected TODOs in the code. But of course everyone can do this as they like! 

Kind regards,
Jörg-Michael

**Comment by matthewdjb** [comment]
For me, it's fine to close.

thanks.

**Comment by ConjuringCoffee** [comment]
I use an ATC variant to find TODO comments, so that isn't really an issue for me 😉
