### ISSUE TITLE
Indentation alignment for multi-line end-of-line comments?

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#310]
Hi,

for my comment style, it would be nice to make this work:
```

            IF comp->name CP '*TIME'.
              DATA(divider) = 1000.  " for better readability, divide all times (except response_time_secs) by 1000 
                                     " (milliseconds instead of microseconds)
            ELSE.
```

instead, I get:

```
            IF comp->name CP '*TIME'.
              DATA(divider) = 1000.  " for better readability, divide all times (except response_time_secs) by 1000 
              " (milliseconds instead of microseconds)
            ELSE.
```

Best regards,
Edo

**Comment by vonglan** [comment]
Hi Jörg-Michael,

I understand that it is a somewhat special request, and I am still a very satisfied customer of ABAPCleaner ;-)

I am pretty sure though, that I have seen that commenting style in books on programming. So it is not completely exotic, in my opinion.
Here is another example, in case you ever want to attack that problem (might be what is meant in #291 as well):

Before:

```
        IF ( line->zStep = '1' AND line->tech_deliveryobstaclecolor IS NOT INITIAL )    " Fehlerliste #23: Obstacle colors only for step 1
        or line->tech_deliveryobstaclecolor na ` gG` .                                  " Fehlerliste #117: also for other steps, if not green

```
After:

```
        IF ( line->zStep = '1' AND line->tech_deliveryobstaclecolor IS NOT INITIAL )    " Fehlerliste #23: Obstacle colors only for step 1
           OR line->tech_deliveryobstaclecolor NA ` gG`.                                  " Fehlerliste #117: also for other steps, if not green

```

The Clean Code rule (put comments before the statement) might be motivated in part by the lack of tools (i.e. necessary manual effort), to keep this commenting style "tidy".
If there was a tool that would help in keeping this commenting style "tidy", it might be a generally worthwhile variant of commenting style.
I use the comments-before-statement for info about _general or important_ structure/logic (if it does not make sense to put it in a separate method), and end-of-line-comments for _details_ or _background_ info.

Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

this … 

> I use the comments-before-statement for info about general or important structure/logic (if it does not make sense to put it in a separate method), and end-of-line-comments for details or background info.

… makes a lot of sense to me, and if you look into the Java code of ABAP cleaner, you will certainly find examples of exactly that ;-) 

And anyway, a lot of "end of line" comments are already out there. Since we definitely shouldn't move them to separate lines, it would certainly help to at least keep them aligned if they already are. Let's see what #291 will develop into! 

Kind regards,
Jörg-Michael
