### ISSUE TITLE
Feature request : Change APPEND to INSERT INTO TABLE 

### ISSUE THREAD

**Issue by matthewdjb** [SAP/abap-cleaner#317]
E.g. 
APPEND wa TO itab.
becomes 
INSERT wa INTO TABLE itab.

APPEND LINES OF this TO that.
becomes
INSERT LINES OF this INTO TABLE that.

In accordance with the Clean Code Style Guide:
https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#prefer-insert-into-table-to-append-to.

**Comment by fabianlupa** [comment]
The style guide lists an exception to the recommendation which I doubt can be detected statically so if this feature were to be added it should be off by default in my opinion.

> Use APPEND TO only if you use a STANDARD table in an array-like fashion, if you want to stress that the added entry shall be the last row.

**Comment by matthewdjb** [comment]
Hmm. I'll put a pull request into the style guide. My view is that you should ALWAYS use INSERT INTO, because if the table type is changed to sorted or hashed, you'll not know there's an issue until you get a dump while testing.

And this has happened in my experience several times.

Strictly, SAP syntax check should spot this, but they're way behind... Here's an opportunity for abap-cleaner to be ahead of the game! :-)

**Comment by se38** [comment]
I'm not seeing any use of APPEND nowadays at all. So yes, +1 on that from my side.

Cheers, Uwe

**Comment by matthewdjb** [comment]
> I'm not seeing any use of APPEND nowadays at all. So yes, +1 on that from my side.
> 
> Cheers, Uwe

I'm dealing with a load of legacy code... 😁

**Comment by matthewdjb** [comment]
Of course INSERT ... INTO TABLE ... for a STANDARD table does put it at the end of the table, so there's really no use for APPEND.

https://help.sap.com/doc/saphelp_nw73ehp1/7.31.19/en-US/fc/eb361f358411d1829f0000e829fbfe/content.htm

**Comment by jmgrassau** [comment]
Hi Matthew, Fabian and Uwe, 

I knew I had seen this discussion somewhere already :-) and indeed, it's our oldest open issue: #8, so let's continue the discussion there. 

Kind regards,
Jörg-Michael

**Comment by fabianlupa** [comment]
You sure have a better memory than me @jmgrassau ;)
