### ISSUE TITLE
Feature request: remove unnecessary CLEAR at the start of a method

### ISSUE THREAD

**Issue by matthewdjb** [SAP/abap-cleaner#319]
I'm seeing code like this:

`METHOD ....
DATA this.
DATA that.

CLEAR l_this, l_that.
...
ENDMETHOD`

Clearly (!) the CLEAR isn't necessary.

**Comment by jmgrassau** [comment]
Hi Matthew, 

have you tried the "Remove needless CLEAR" rule? ;-)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/f71bcde1-1c4b-4b42-b4e8-f36cd7d0297e)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/f84d3a19-4cd1-41f1-bc3d-38da2eb81a84)

Kind regards,
Jörg-Michael

**Comment by matthewdjb** [comment]
Hah. Didn't notice that. Strangely I wasn't getting the TODO, but the delete works fine.

**Comment by jmgrassau** [comment]
Hi Matthew, 

no problem at all – as always, we rather get a good idea twice than missing one!

Kind regards,
Jörg-Michael
