### ISSUE TITLE
Packaging: Jar file contains resources twice

### ISSUE THREAD

**Issue by agoeb** [SAP/abap-cleaner#325]
I just noticed that the release jar file for ABAP Cleaner contains all the text files twice (see screenshot from a zip file viewer).

![jar-contents](https://github.com/SAP/abap-cleaner/assets/2226123/25fde16f-8e4a-40ff-a7bc-371de943c9f1)

While that might not be an immediate issue and may not even increase file size due to compression, it still might become an issue at some point, as some parts for the code might read these resource files from one location, and others might access them using their other paths, leading to technical debt down the road.

I have not yet investigated the build pipeline to find the reason for this, because I am interested in whether this is even something you would like to address at all.

Thanks!

**Comment by jmgrassau** [comment]
Hi Andreas, 

ah, well spotted, thanks for reporting this! It seems to me that the build.properties of com.sap.adt.abapcleaner has one include too many, we're checking this! (And yes, it seems this would indeed reduce compressed JAR file size by 2.3 MB!) 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Andreas, 

thanks again – this will be fixed with the next release!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Andreas, 

thanks again for opening this issue! This should now be fixed with version 1.17.1, which was just released – the JAR file is now approx. 2 MB smaller :-)

Kind regards,
Jörg-Michael

**Comment by agoeb** [comment]
Hi Jörg-Michael,

Thanks a lot! Your responsiveness is very encouraging and motivates me to voice other topics in the future as well.

Regards,
Andreas
