### ISSUE TITLE
Feature Request: Captions for Read-Only Code Preview

### ISSUE THREAD

**Issue by MichiFr** [SAP/abap-cleaner#336]
Hi!

Would it be possible that the code preview window gets a caption line above bothe code blocks, reading e.g. "Before" and "After" or similar?

This would be easier to understand which side of the preview is the old formatting and which one is the new one.
![image](https://github.com/SAP/abap-cleaner/assets/28045390/d168ac9b-80c6-4fed-9bd2-21547f4cb6e8)

Thanks,
Michael

**Comment by jmgrassau** [comment]
Hi Michael, 

thanks for this, @ConjuringCoffee will be happy for the support of #249 :-) (And yes, since the Comparison view in ADT sometimes has the reverse order, it would certainly be clearer to put this information on top).

Kind regards,
Jörg-Michael

**Comment by MichiFr** [comment]
OK, so I gave #249 a vote ^^
