### ISSUE TITLE
CLI parameter `--version` to show version

### ISSUE THREAD

**Issue by bnichell** [SAP/abap-cleaner#339]
It could be helpful to add a CLI parameter, which logs the ABAP cleaner version to stdout.
This could be interesting for instance in CI, when it needs to be confirmed that the existing ABAP cleaner has the required version.
The parameter could be provided as `--version` and `-v`

**Comment by bnichell** [comment]
Sure, that is great.
Thank you very much!

**Comment by jmgrassau** [comment]
Hi Benedikt, 

thanks for the idea! This parameter should now be available with version 1.21.0, which was just released!

Kind regards,
Jörg-Michael
