### ISSUE TITLE
Alignment of method declarations with ABSTRACT

### ISSUE THREAD

**Issue by blackfish5** [SAP/abap-cleaner#354]
Hi,

alignment of method declared as ABSTRACT does now work as expected:

before cleaner:
![image](https://github.com/user-attachments/assets/045a78e7-625b-4230-a07c-e252d5694840)

after cleaner:
![image](https://github.com/user-attachments/assets/c23b665e-2b10-4dba-bbce-31e4d791a5cc)

Thanks for checking
M.

**Comment by jmgrassau** [comment]
Hi blackfish5, 

thanks for reporting this! This bug should be fixed with the next release, with ABSTRACT getting an own "column" now:

![image](https://github.com/user-attachments/assets/eaadb9de-788b-4740-adeb-1b0814695995)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi blackfish, 

thanks again for reporting this issue – this should now be fixed in version 1.19.3, which was just released!

Kind regards,
Jörg-Michael
