### ISSUE TITLE
Doesn't show in menu on Mac 

### ISSUE THREAD

**Issue by renivaldo82** [SAP/abap-cleaner#37]
I installed the plugin but doesn't show items in menu, I try install agin but doesn't work.
I use eclipse on Mac, does work on eclipse on Mac?

**Comment by jelliottp** [comment]
It is working fine for me on Mac, other than the shortcut for interactive cleanup is the same as screenshot.

**Comment by renivaldo82** [comment]
> It is working fine for me on Mac, other than the shortcut for interactive cleanup is the same as screenshot.

Here doesn't show on menu

**Comment by renivaldo82** [comment]
![Screen Shot 2023-05-29 at 09 34 23](https://github.com/SAP/abap-cleaner/assets/11511239/b04f9c75-8b8e-47ec-b250-f1fdd7c8f5a8)
![Screen Shot 2023-05-29 at 09 21 08](https://github.com/SAP/abap-cleaner/assets/11511239/50542512-c49b-431d-81e6-3d8c777b14e0)

**Comment by renivaldo82** [comment]
> Hi Renivaldo,
> 
> meanwhile, I asked a colleague who knows better about Mac than me, but he confirmed that from the screenshots, everything looks fine, so it's hard to understand why the menu isn't showing.
> 
> Maybe the error log contains some hints? (menu "Help / Collect Support Information…") If you'd like us to take a look, you could send them to "abap-cleaner at sap dot com" (but no guarantees I can really help…)
> 
> Kind regards, Jörg-Michael

Hi the log shows nothin.

**Comment by jmgrassau** [comment]
Hi Renivaldo, 

hm, sort of running out of ideas here what could have gone wrong. Maybe you could try on a fresh Eclipse + ADT installation?

Kind regards,
Jörg-Michael
