### ISSUE TITLE
Error on executing rule "Make implicit type explicit"

### ISSUE THREAD

**Issue by Ronson1909** [SAP/abap-cleaner#375]
message

20241111_163513 Make implicit type explicit, line 54: Error executing rule 'Make implicit type explicit': cannot insert a right sibling to a token that opens a level

![image](https://github.com/user-attachments/assets/4aa291d5-7b17-426d-b9ee-dbe44bf5b900)

in the "Profiles and Rules" Dialogue in the rule rule "Make implicit type explicit" when unchecking "Replace parentheses with LENGTH" while the 3 other options are ticked with the sample code.

Software version 1.20.0

**Comment by jmgrassau** [comment]
Hi Ronson1909, 

oops, this combination of settings was indeed not considered, thanks for reporting this! It will be fixed in the next release: 

![image](https://github.com/user-attachments/assets/09b6bfd0-49ae-499f-be2e-e51a4bfba145)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Ronson1909, 

thanks again for reporting this! This should now be fixed with version 1.21.0, which was just released!

Kind regards,
Jörg-Michael
