### ISSUE TITLE
Indentation of CATCH with multiple exception classes

### ISSUE THREAD

**Issue by vonglan** [SAP/abap-cleaner#376]
Hi,
it seems this does not work yet.

```
      CATCH zcx_ycf_data_not_found
    cx_sy_conversion_no_number.
        granularity = -1.
    ENDTRY.

```

I would like:

```
      CATCH zcx_ycf_data_not_found
            cx_sy_conversion_no_number.
        granularity = -1.
    ENDTRY.

```
or

```
      CATCH zcx_ycf_data_not_found cx_sy_conversion_no_number.
        granularity = -1.
    ENDTRY.
```

Best regards,
Edo

**Comment by jmgrassau** [comment]
Hi Edo, 

good idea – this could either be a new cleanup rule, or we could add it to "Align CLEAR:, FREE: and SORT", with a similar selection ("Use one line per exception class: Always | Never" + maximum line length)

Kind regards,
Jörg-Michael

**Comment by vonglan** [comment]
Hi Jörg-Michael,
I think this is similar to SORT. So either include in existing rule, or split this into two rules (CLEAR+FREE vs SORT+CATCH)
Best regards,
Edo
