### ISSUE TITLE
Feature Request: Alignment for RAISE EVENT statements

### ISSUE THREAD

**Issue by StefanRutzmoser** [SAP/abap-cleaner#377]
The new feature should align the code similar to what it does for CALL METHOD. But examples are better than describing it in words:

Before cleanup:
```
RAISE EVENT message
EXPORTING
iv_id = 'MSG_ID'
iv_type = 'E'
iv_number = '001'.
```

After cleanup:
```
RAISE EVENT message
  EXPORTING
    iv_id     = 'MSG_ID'
    iv_type   = 'E'
    iv_number = '001'.
```

Optionally put the EXPORTING in the line of the statement:
```
RAISE EVENT message EXPORTING
  iv_id     = 'MSG_ID'
  iv_type   = 'E'
  iv_number = '001'.
```

I'm not sure if a new rule is needed for this or it could/should be added to the existing "Align parameters and components" rule.

**Comment by jmgrassau** [comment]
Hi Stefan, 

perfect, very nice enhancement of the "Align parameters and components" rule!

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Stefan, 

this was literally one added line of code! The layout simply follows the options for procedural calls (same as CALL METHOD, CREATE OBJECT, RECEIVE RESULTS, RAISE EXCEPTION, and RAISE SHORTDUMP):

![image](https://github.com/user-attachments/assets/71dce152-a622-463e-9d35-a8a63fbc41aa)

![image](https://github.com/user-attachments/assets/e8d06306-398a-471e-a7c6-68037ff4feb1)

Kind regards,
Jörg-Michael
