### ISSUE TITLE
" TODO: variable is assigned but never used (ABAP cleaner) after checking whether a database entry exists

### ISSUE THREAD

**Issue by JanisBur** [SAP/abap-cleaner#38]
Sometimes I just want check, whether a database entry exists using the sy-subrc variable. I am forced to select the data into some table/structure, because a "SELECT" without "INTO" is not possible.

`" TODO: variable is assigned but never used (ABAP cleaner)
SELECT SINGLE * FROM pa0000 INTO @DATA(ls_dummy) WHERE  begda <= @sy-datum
                                                   AND  endda >= @sy-datum.

IF sy-subrc = 0.
  " further processing
ENDIF.`

Would it be possible to switch the message "TODO: variable is assigned but never used (ABAP cleaner)" off in such cases?

**Comment by jmgrassau** [comment]
Hi JanisBur, 

I think the best way to suppress this would be to add a ```##NEEDED``` pragma at the end of the line of ```@DATA(ls_dummy)```. With this, ABAP cleaner will not add such a TODO comment (in fact, it will even automatically remove the existing one). Without ```##NEEDED```, the Extended Check (transaction SLIN) would also create a Field Attributes warning:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/621c8046-1e15-439a-bb8e-4b7aa0d7e80d)

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
This wasn't clear to me. I really like how it even automatically removes its own comment. How about adding examples to the rule to demonstrate the use of `##NEEDED`?

**Comment by fabianlupa** [comment]
@JanisBur For the existence check I usually do this instead:
```abap
SELECT COUNT(*)
  FROM pa0000
  WHERE begda <= @sy-datum
    AND endda >= @sy-datum.
IF sy-dbcnt >= 1.
  " further processing
ENDIF.
```
Or even this:
```abap
SELECT SINGLE @abap_true
  FROM pa0000
  WHERE begda <= @sy-datum
    AND endda >= @sy-datum
  INTO @DATA(exists).
IF exists = abap_true.
  " further processing
ENDIF.
```
Do note using COUNT bypasses the table buffer implicitly compared to the other solutions.

**Comment by jmgrassau** [comment]
Hi JanisBur and @ConjuringCoffee, 

in version 1.3.0, the example of the "Delete unused variables" rule is now enhanced to make the effect of the ```##NEEDED``` pragma a bit more visible:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/25ea481f-2033-4819-921c-8f0860f5f638)

Kind regards,
Jörg-Michael
