### ISSUE TITLE
Not able to install abap-cleaner into Eclipse 2024-09 version

### ISSUE THREAD

**Issue by Nikesh1993** [SAP/abap-cleaner#393]
Hi Experts,

I have followed the steps mentioned to install abap-cleaner add-on to my Eclipse ADT.
During installation time, I faced the below error. I'm not able to understand why this error is coming and how to resolve this error.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Can't download artifact osgi.bundle,com.sap.adt.abapcleaner,1.21.1 required by com.sap.adt.abapcleaner[1.21.1], com.sap.adt.abapcleaner.feature.feature.group[1.21.1], com.sap.adt.abapcleaner[1.21.1], com.sap.adt.abapcleaner.gui[1.21.1] from any of the following repositories: 
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/p2/org.eclipse.equinox.p2.core/cache/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/configuration/org.eclipse.osgi/403/data/listener_1925729951/
file:/C:/Program%20Files/Eclipse%20IDE%202024/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/.eclipseextension
https://download.eclipse.org/eclipse/updates/4.33
https://download.eclipse.org/releases/2024-09
https://download.eclipse.org/mylyn/updates/release/4.5.0
https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0
https://download.eclipse.org/lsp4j/updates/releases/0.23.1
https://download.eclipse.org/technology/m2e/releases/latest
https://download.eclipse.org/lsp4e/releases/0.26.6
https://download.eclipse.org/webtools/downloads/drops/R3.35.0/R-3.35.0-20240825085431/repository
https://tools.hana.ondemand.com/latest
https://download.eclipse.org/webtools/repository/latest
https://download.eclipse.org/technology/epp/packages/latest/
https://download.eclipse.org/releases/latest
https://download.eclipse.org/justj/epp/release/latest
https://download.eclipse.org/tm4e/releases/0.14.0
https://download.eclipse.org/modeling/emf/emf/builds/release/2.40.0
https://download.eclipse.org/egit/updates-7.1
https://download.eclipse.org/wildwebdeveloper/releases/1.3.9
https://download.eclipse.org/justj/jres/21/updates/release/latest
Can't download artifact org.eclipse.update.feature,com.sap.adt.abapcleaner.feature,1.21.1 required by com.sap.adt.abapcleaner.feature.feature.jar[1.21.1], com.sap.adt.abapcleaner.feature.feature.group[1.21.1], com.sap.adt.abapcleaner.feature.feature.jar[1.21.1] from any of the following repositories: 
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/p2/org.eclipse.equinox.p2.core/cache/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/configuration/org.eclipse.osgi/403/data/listener_1925729951/
file:/C:/Program%20Files/Eclipse%20IDE%202024/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/.eclipseextension
https://download.eclipse.org/eclipse/updates/4.33
https://download.eclipse.org/releases/2024-09
https://download.eclipse.org/mylyn/updates/release/4.5.0
https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0
https://download.eclipse.org/lsp4j/updates/releases/0.23.1
https://download.eclipse.org/technology/m2e/releases/latest
https://download.eclipse.org/lsp4e/releases/0.26.6
https://download.eclipse.org/webtools/downloads/drops/R3.35.0/R-3.35.0-20240825085431/repository
https://tools.hana.ondemand.com/latest
https://download.eclipse.org/webtools/repository/latest
https://download.eclipse.org/technology/epp/packages/latest/
https://download.eclipse.org/releases/latest
https://download.eclipse.org/justj/epp/release/latest
https://download.eclipse.org/tm4e/releases/0.14.0
https://download.eclipse.org/modeling/emf/emf/builds/release/2.40.0
https://download.eclipse.org/egit/updates-7.1
https://download.eclipse.org/wildwebdeveloper/releases/1.3.9
https://download.eclipse.org/justj/jres/21/updates/release/latest
Can't download artifact osgi.bundle,com.sap.adt.abapcleaner.gui,1.21.1 required by com.sap.adt.abapcleaner.gui[1.21.1], com.sap.adt.abapcleaner.feature.feature.group[1.21.1], com.sap.adt.abapcleaner[1.21.1], com.sap.adt.abapcleaner.gui[1.21.1] from any of the following repositories: 
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/p2/org.eclipse.equinox.p2.core/cache/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/configuration/org.eclipse.osgi/403/data/listener_1925729951/
file:/C:/Program%20Files/Eclipse%20IDE%202024/
file:/C:/Users/insinghni/.eclipse/org.eclipse.platform_4.33.0_241937675_win32_win32_x86_64/.eclipseextension
https://download.eclipse.org/eclipse/updates/4.33
https://download.eclipse.org/releases/2024-09
https://download.eclipse.org/mylyn/updates/release/4.5.0
https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.33.0
https://download.eclipse.org/lsp4j/updates/releases/0.23.1
https://download.eclipse.org/technology/m2e/releases/latest
https://download.eclipse.org/lsp4e/releases/0.26.6
https://download.eclipse.org/webtools/downloads/drops/R3.35.0/R-3.35.0-20240825085431/repository
https://tools.hana.ondemand.com/latest
https://download.eclipse.org/webtools/repository/latest
https://download.eclipse.org/technology/epp/packages/latest/
https://download.eclipse.org/releases/latest
https://download.eclipse.org/justj/epp/release/latest
https://download.eclipse.org/tm4e/releases/0.14.0
https://download.eclipse.org/modeling/emf/emf/builds/release/2.40.0
https://download.eclipse.org/egit/updates-7.1
https://download.eclipse.org/wildwebdeveloper/releases/1.3.9
https://download.eclipse.org/justj/jres/21/updates/release/latest

**Comment by jmgrassau** [comment]
Hi Nikesh1993, 

have you tried the solutions listed on [Knows Installation Issues](https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md), including the first one regarding eclipse.ini?

Kind regards,
Jörg-Michael

**Comment by Nikesh1993** [comment]
> Hi Nikesh1993,
> 
> have you tried the solutions listed on [Knows Installation Issues](https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md), including the first one regarding eclipse.ini?
> 
> Kind regards, Jörg-Michael

Hi jmfrassau,

Yes. I have added the two lines in eclipse.ini file and now it is coming below error and abap-cleaner is not able to download.

![Image](https://github.com/user-attachments/assets/d917f79b-3740-47ac-a4d1-dae7d80c4b13)

**Comment by Nikesh1993** [comment]
The problem was solved after I re-installed the eclipse.

**Comment by jmgrassau** [comment]
perfect, thanks! Then I hope using ABAP cleaner will be a smoother experience than installing it was!
