### ISSUE TITLE
Profile creation box is not completely visible

### ISSUE THREAD

**Issue by GPR8** [SAP/abap-cleaner#40]
Hi everyone,

When creating a new profile I'm experiencing some problems seeing the Profile creation box as show bellow, I mean, the buttons are not clearly visible.. Does this happen to anyone else?

![image](https://github.com/SAP/abap-cleaner/assets/39055226/9b0b7aa8-2ac8-42e6-b206-2b78a15c2123)

Thanks!

**Comment by jmgrassau** [comment]
Hi GPR8, 

thanks for reporting this – that's odd, it was even like this in the graphical editor … Trying a different layout manager now:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/5b760f01-dce6-4dce-98b8-f76a2bebd2b1)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi @ConjuringCoffee, 

yes, I wonder whether this depends on display scale (125% in my case) or OS window title height (taking away a higher or lower number of pixels from the control area)? Hope the other layout manager does that better… 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi GPR8, 

the fix is now released with version 1.3.0 – hope the dialog is completely visible now!

Kind regards,
Jörg-Michael

**Comment by GPR8** [comment]
Hi @jmgrassau,

Thank you for the update!

I was checking and this problem is indeed because of the scaling of the screen. Not sure if you have any chance to dynamically adapt it to the actual pc scaling settings, but anyway it's better for me now:
 
![scale_settings](https://github.com/SAP/abap-cleaner/assets/39055226/25e04567-aedf-482c-9efa-bd0d027aa787)
![ProfileBox_150%](https://github.com/SAP/abap-cleaner/assets/39055226/521d48f7-49c6-46a6-adae-0b9ca1464618)
![ProfileBox_125%](https://github.com/SAP/abap-cleaner/assets/39055226/d3c0a49a-ff81-4f5d-ae2a-abf690a1bdda)

Thanks!
