### ISSUE TITLE
Dark theme problems with highlight options on settings screen

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#47]
The "Highlight" options on the screen "Profiles and Rules" doesn't seem to support dark mode:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/9234b0b6-72a9-46c9-a7f7-410acc229d99)

Here are my appearance settings:
![image](https://github.com/SAP/abap-cleaner/assets/72548231/bd3dc36f-1158-4383-8d54-ad9cf51ddb84)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

thanks for reporting this – should be fixed in the next release!

Kind regards,
Jörg-Michael
