### ISSUE TITLE
Feature request: Allow temporary changes to examples in rule settings

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#48]
Each rule has some examples that immediately show the result of the selected rule options. With this issue I'd like to request being able to edit the code from the example directly. This would make testing the settings easier and faster.

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

I suppose you are aware of the "Paste" button to test cleanup rules and settings on your own code…

![image](https://github.com/SAP/abap-cleaner/assets/79639298/add7c544-312e-4da3-9133-36f9554eb0ba)

… so this is about being able to then modify the code directly inside the ABAP cleaner example, right? I do see your point – I usually use Notepad++ to experiment with own code snippets and then copy/paste them into the examples section; and these copy/paste shortcuts could of course be saved with this idea. 

Currently, this control is a paintable Canvas to give ABAP cleaner complete freedom on how to display the code. Replacing it with an editable control would be possible, but I don't think we could then easily have the same code coloring, highlighting of changes etc. – that would simply be a bit much just for this purpose. 

So, nice idea, but from effort perspective most probably a "won't fix", at least from my end. 

Kind regards,
Jörg-Michael
