### ISSUE TITLE
Replace "measure" by "action"

### ISSUE THREAD

**Issue by bjoern-jueliger-sap** [SAP/abap-cleaner#52]
There's a [bunch of places](https://github.com/search?q=repo%3ASAP%2Fabap-cleaner%20measure&type=code) that use "measure" to mean "action" (probably a direct translation of the German *Maßnahme*), in particular this config UI for the "Delete unused variables" rule:
![image](https://github.com/SAP/abap-cleaner/assets/50877303/ad5eecab-4efd-41b5-a7c3-1b03cdab1951)

While measure *can* mean "action" (as in "We've taken measures to clean up our code"), the use of measure to denote a specific repeatable action in the context of a tool like this strikes me as unidiomatic.

(not a pull request because I'd like native speakers' input on this before changing it)

**Comment by jmgrassau** [comment]
Hi Björn, 

I just got confirmation from a native speaker (and computer expert) that "action" is indeed better. Will correct this!

Kind regards,
Jörg-Michael
