### ISSUE TITLE
Format SQL statements

### ISSUE THREAD

**Issue by christianguenter2** [SAP/abap-cleaner#6]

**Comment by jmgrassau** [comment]
Hi Christian, 

that's of course a great idea, but also a rather complex one… So, for "expectation management", please don't expect this too be implemented too soon (at least not by me); but it is definitely on the wish list!

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
Any update on this? Is it still planned or in-progress?

I definitely understand the complexity here. Have we considered a thin-slicing approach rather than tackling it all at once? For example, an MVP could be simply formatting with consistent indentation. Then later options for formatting the field list,  aligning conditions, etc.

**Comment by jmgrassau** [comment]
Hi Christian, 

thanks a lot for opening this issue and for your patience! From the SELECT statements that I saw, there were just too many coding styles to fit all required options into one cleanup rule, so I actually created three of them: 

* **Align SELECT clauses** aligns the keywords SELECT, FROM, FIELDS, WHERE, GROUP BY etc. in (main- or sub-)query clauses (but doesn't care for anything after the keywords), e.g.
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/77c5018c-f561-4b87-88b6-38caedd5e4b7)
* **Align SELECT ... FROM ... JOIN** aligns the FROM clause, including joins (don't worry, the cascade-style layout in the example of course not the only layout possible…), e.g. 
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/d8073274-1d42-4e44-975b-50d3d4e3d7eb)
* **Align SELECT lists** aligns the field lists after SELECT, FIELDS, ORDER BY, GROUP BY, and INTO ( ... ), allowing for both multi-line or single-line layout (or deriving that from the majority of elements in the list):
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/7f574b3e-45f2-4814-81f6-ddb3f7bb6442)
* **Align logical expressions** was enhanced to also align conditions after JOIN … ON, WHERE, HAVING, and CASE … WHEN:
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/102b2edc-8bae-47b4-88a7-7e058653da3e)

And yes, you can configure the results ;-)

* **Align SELECT clauses**:
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/64d32abc-601a-4ef4-960c-cdc6fb115bf2)
* **Align SELECT ... FROM ... JOIN**:
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/86ecd5f9-f38c-48a3-8237-d703478fb7ea)
* **Align SELECT lists**:
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/0a722105-d8b6-44fc-9c30-bf057babadc6)
* **Align logical expressions**:
  ![image](https://github.com/SAP/abap-cleaner/assets/79639298/0dbd9454-329a-428f-9a62-30f8a0ad5eca)

Hope this works for you! 

Kind regards,
Jörg-Michael

**Comment by christianguenter2** [comment]
Thx a lot. I'll give a try 👍

**Comment by kaisicker** [comment]
Thanks a lot!
