### ISSUE TITLE
Feature request: Remove end-of comments

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#60]
Hi Jörg-Michael, I'd like to request a feature to remove end-of-comments.

This refers to a rule from Clean ABAP: [Don't add method signature and end-of comments](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#dont-add-method-signature-and-end-of-comments)

Example, before:

```abap
FORM execute.
ENDFORM.              " EXECUTE
```

Expected result:

```abap
FORM execute.
ENDFORM.            
```

Below are some more examples.

```abap
METHOD execute.
ENDMETHOD. " execute
```

```abap
MODULE user_command_0600 INPUT.
ENDMODULE. " USER_COMMAND_0600  INPUT
```

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

oh yes, that's a nice one! I just checked a few MB of code and found countless examples where such end-of-comments could be removed after ENDCLASS, ENDINTERFACE, ENDMETHOD, ENDFORM, ENDCASE, ENDLOOP, ENDIF etc. 

However, some cases did actually contain relevant information, so the rule would have to check whether the comment simply repeats parts of the corresponding CLASS, INTERFACE, METHOD etc. statement and only remove those. And it should allow for some flexibility, e.g. sometimes ABAP words are repeated (and prefixes / underscores are omitted), as in 

```ABAP
CLASS lcl_any_class IMPLEMENTATION.
  METHOD handle_errors.
    LOOP AT lts_error_contract ...
    ENDLOOP. " AT error contract
  ENDMETHOD. " handle errors
ENDCLASS. " lcl_any_class IMPLEMENTATION
```

What we won't be able to eliminate this way, regrettably, are copy errors such as:

```ABAP
METHOD other_method.
  ...
ENDMETHOD.      " any_method
```

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
I support this as a feature as well. I rarely, if ever, have seen a useful comment on the end of a statement. Perhaps this could be an option of the rule to either remove all, or only “repeated” information.

**Comment by fabianlupa** [comment]
I suppose you can always remove them if the comments are exactly as generated by the IDE. I doubt anyone adjusted the generation patterns in the last two decades ;)

**Comment by fabianlupa** [comment]
Similar thing with these generated headers no one ever adjusts and is too lazy to delete by the way.

![image](https://github.com/SAP/abap-cleaner/assets/5270359/35ed9fd2-0d5e-4213-b627-6f885d7e4d29)

**Comment by jmgrassau** [comment]
Hi @ConjuringCoffee, @jelliottp and @fabianlupa, 

here's what the upcoming "Remove end-of comments" rule does :-)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/74102804-e466-4bfe-bf66-e0a4a48215c6)

If in the options …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c02429e0-d91f-4aa5-9148-698d97522c5c)

… you select "**always remove**", you could even get rid of the comments in line 24 and 38. Maybe you'd only want that on ```ENDMETHOD``` and ```ENDCLASS``` level, where you'd frequently find auto-generated end-of comments.

With "**remove if redundant**" (= default), such comments are only removed if they more or less repeat the (start of) the opening command – "more or less" meaning that ABAP words could be skipped, underscores could be spaces, prefixes like ```lts_``` could be omitted, upper/lower case is ignored etc. (see examples above).

Generated headers should be removed by a different cleanup rule, I think.

Kind regards,
Jörg-Michael

**Comment by se38** [comment]
What will be the default?
Suggestion: "always keep" inside methods and "remove If redundant" at ENDMETHOD/ENDCLASS

>

**Comment by jelliottp** [comment]
> With "**remove if redundant**" (= default), such comments are only removed if they more or less repeat the (start of) the opening command – "more or less" meaning that ABAP words could be skipped, underscores could be spaces, prefixes like `lts_` could be omitted, upper/lower case is ignored etc. (see examples above).
>

To clarify: does this mean for example, if line 19 contained `" LOOP at ls_item-inner_item` it would also get removed?

**Comment by jmgrassau** [comment]
Hi Josh, 

exactly – if the opening command reads ```LOOP AT lts_any_table INTO DATA(ls_struc)```, then any of the following comments would be regarded as redundant:

```ABAP
ENDLOOP. " lts_any_table
ENDLOOP. " LTS_ANY_TABLE
ENDLOOP. " any table
ENDLOOP. " AT any table
ENDLOOP. " LOOP AT any table
ENDLOOP. " LOOP lts_any_table
ENDLOOP. " lts_any_table INTO DATA(ls_struc)
...
```

So the rule tries to 'match' the whole comment, but tolerates any skipped ABAP words. Identifiers must not be skipped, but their underscores may be spaces, and the bit before the first underscore may be skipped (assuming it could be a prefix). As soon as the whole comment is consumed, it is regarded a match (regardless of whether or not the opening command continues). 

Kind regards,
Jörg-Michael

**Comment by se38** [comment]
The comments inside a method are all "hands made", so someone thought, this comment would be helpful and should be kept by default.
The ENDMETHOD/ENDCLASS/ENDPERFORM are generated in GUI-mode and are useless (imho)

**Comment by jelliottp** [comment]
Thanks for clarifying. I think this looks great and helps reduce manual cleanup time.

**Comment by jmgrassau** [comment]
Hi Uwe, 

yes, I see your point, it would definitely be the more careful default. On the other hand, even 'hand made' comments of this sort are advised against by the style guide:

```ABAP
" anti-pattern
METHOD get_kpi_calc.
  IF has_entries = abap_false.
    result = 42.
  ENDIF.  " IF has_entries = abap_false
ENDMETHOD.   " get_kpi_calc
```

From what I've seen, you usually find them in veeeery long methods with breathtaking nesting depth and a strict 'structured programming' approach (where methods should always have exactly one entry point and one exit point, and it is therefore seen as good style to make an ```IF its_contract IS NOT INITIAL ... ENDIF``` span the entire 400 lines of the method), e.g. 

```ABAP
* the opening statements for the following are 400 lines further up the method

            ENDLOOP. " ls_item-subitem
          ENDIF. " ls_item-validaty < sy-datum
        ENDIF. " ls_item-processable = 'X'
      ENDLOOP. " item
    ENDLOOP. " contract
  ENDIF. " contract IS NOT INITIAL
ENDMETHOD. " process_items
```

It could be argued, of course, that the line-end comments are the least of your worries (and maybe indeed helpful) if you have to deal with code like that… So maybe an "line limit" option would make sense?

Kind regards,
Jörg-Michael

**Comment by se38** [comment]
I know exactly these kind of programs 🤬
Line limit would be nice, but low prio from my side

**Comment by jmgrassau** [comment]
Hi all, 

closing this since the cleanup rule "Remove end-of comments" is now available, while the other point of removing auto-generated method signatures can be handled as part of a new cleanup rule for issue #152. (The styleguide has both points in its chapter [Don't add method signature and end-of comments](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#dont-add-method-signature-and-end-of-comments), but that doesn't mean it has to be the same cleanup rule, of course). 

Kind regards,
Jörg-Michael
