### ISSUE TITLE
Default cleanup range 'Current class' does not work (as expected?)

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#62]
Hi Jörg-Michael,

I have found that the default cleanup range "Current class" does not work the way I expected it to. Here's a global class as an example:

```abap
CLASS ycl_cleaner_example DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    methods example.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_cleaner_example IMPLEMENTATION.
  METHOD example.

  ENDMETHOD.

ENDCLASS.
```

If I place my cursor inside the method implementation, then I would have expected the cleanup range to target the entire class. However, it only applies to the method:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/63421eb2-9622-4073-bb2f-b060ce36d895)

Is this a bug or am I just misinterpreting the option?

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

yes, you're right – but it's not really a bug: In includes, you do not always have the class DEFINITION directly next to the IMPLEMENTATION (but rather, three different classes may be defined before then the three implementations follow); but the cleanup range currently is a single range of lines only. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

FYI, I now enhanced the documentation on the [Default cleanup range](https://github.com/SAP/abap-cleaner/blob/main/docs/main-window.md#default-cleanup-range) accordingly.

Kind regards,
Jörg-Michael
