### ISSUE TITLE
Rearrange local declarations leading to syntax error

### ISSUE THREAD

**Issue by zmsMarc** [SAP/abap-cleaner#64]
Settings: Default
![grafik](https://github.com/SAP/abap-cleaner/assets/9104198/8e59e671-53bc-4b2f-8a4c-81ba30b73080)

I was working on changes to AbapOpenCheck 06 (https://github.com/larshp/abapOpenChecks/blob/main/src/checks/zcl_aoc_check_06.clas.abap) and noticed a syntax error after AbapCleaner re-ordered the local declarations.

Here's an example with the basic structure before:
![grafik](https://github.com/SAP/abap-cleaner/assets/9104198/2e395c63-81d4-4ff5-a6c4-39cfdd36e328)

And after Cleanup:
![grafik](https://github.com/SAP/abap-cleaner/assets/9104198/20d3398b-3e5d-4585-815c-46744e19cba2)

Notice the field symbol declaration is now before the data statement it references.

Maybe there needs to be an additional check on usages of LIKE LINE OF.

**Comment by jmgrassau** [comment]
Hi Marc, 

thanks again for this finding! This will be fixed in the next release – the rule now double-checks that a declaration is not moved in front of the declaration it refers to with ```LIKE```.

Kind regards,
Jörg-Michael

**Comment by zmsMarc** [comment]
Thanks as always for the quick solution!
