### ISSUE TITLE
Aligning single parameters for functional calls

### ISSUE THREAD

**Issue by jelliottp** [SAP/abap-cleaner#66]
I am using the "Align parameters and components" rule with the following settings:
![image](https://github.com/SAP/abap-cleaner/assets/63249342/39c68c61-a700-43a0-9a20-f51aec817137)

Typically we are allowing one parameter behind functional calls since that would keep it on one line. This keeps it nice and tidy for exporting parameters, but the issue arises when `IMPORTING` or `CHANGING` is involved. The rule is then enforcing this type of format which I'd be surprised if anyone wanted:
```
class->method( CHANGING
                 field = value ).
```

I would like to see it still kept on the one line:
```
class->method( CHANGING field = value ).
```

Is there a way to accomplish this with the current settings? Or can it be tweaked to allow for this? I wouldn't want to uncheck "put keywords on own line", because then that negatively affects the scenarios where there are multiple parameters.

**Comment by jmgrassau** [comment]
Hi Josh, 

good point – I completely agree that no-one would want …

```ABAP
class->method( CHANGING
                 field1 = value1 ).
```

That was easy to fix. However, what should be done if someone configures this:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/47ef39aa-38a7-41af-9e75-e09c7d4d236a)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/25b57fc0-c939-4654-adb4-4baee06f0001)

Should the rule then continue after the keywords as well (ignoring the second setting) …

```ABAP
class->method( CHANGING field1 = value1
                        field2 = value2
                        field3 = value3 ).
```

… or would you then rather expect …

```ABAP
class->method( CHANGING
                 field1 = value1
                 field2 = value2
                 field3 = value3 ).
```

… for cases that are not one-liners?

Not sure here. We could of course turn the "…put keywords … on own line" into a selection, e.g. "Always / Only below the call / Never"; then the second option would 'allow' us to behave differently if we continue after the call.

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Josh, 

perfect, then the behavior for >1 parameter is as you would expect it, too. Unless someone explicitly wants >1 parameters cases to look different, we can close this for now! 

Kind regards,
Jörg-Michael
