### ISSUE TITLE
"Align parameters and components": Direct usage of structure looks weird in VALUE

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#70]
Here's an example I don't want the ABAP Cleaner to change any further:

```abap
    DATA line_1 TYPE bapiret2.
    DATA table_1 TYPE bapiret2_t.

    table_1 = VALUE #( ( line_1 )
                       ( log_msg_no = '1' ) ).
```

Unfortunately, the ABAP Cleaner aligns the structure to the other assignments:

```abap
    DATA line_1 TYPE bapiret2.
    DATA table_1 TYPE bapiret2_t.

    table_1 = VALUE #( (              line_1 )
                       ( log_msg_no = '1' ) ).
```

Is this on purpose? If it is, can we please get an option to turn it off? 😊

Here are the settings I use:

![image](https://github.com/SAP/abap-cleaner/assets/72548231/4bcb3790-5f65-4433-b215-20d34936be6b)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

ah, nice example, I'm afraid this was simply not considered yet! 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
P.S.: And I can't imagine anyone wanting the current behavior, so I think this could be fixed without an additional option :-)

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

okay, this should be fixed in the next release!

Kind regards,
Jörg-Michael
