### ISSUE TITLE
Differences with ABAP Formatter

### ISSUE THREAD

**Issue by jelliottp** [SAP/abap-cleaner#73]
I think this has come up before, but it would be good if abap-cleaner doesn't unintentionally contradict the basics of what the ABAP formatter will do. Some findings:

1. Text Elements: The Formatter considers TEXT a keyword so if you are using uppercase it does this `TEXT-01` but abap cleaner forces lowercase `text-01`.
2. Program selection screen definitions: The Formatter will force everything to have no indentation, but abap-cleaner adds indentation. Assuming this is this intended?
```
SELECTION-SCREEN BEGIN OF BLOCK block WITH FRAME TITLE text-01.
  PARAMETERS param1 RADIOBUTTON GROUP r1.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS param2 RADIOBUTTON GROUP r2.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK block.
```
3. Sometimes I see nested types used, and the indentation isn't quite right. I'd want this, which is what the Formatter does:
```
TYPES:
  BEGIN OF some_type.
    INCLUDE TYPE nested_type.
    TYPES: field TYPE some_field,
  END OF some_type.
```
But abap-cleaner does this:
```
TYPES: BEGIN OF some_type.
         INCLUDE TYPE nested_type.
TYPES:   field TYPE some_field,
       END OF some_type.
```

**Comment by fabianlupa** [comment]
The ABAP formatter actually does format those examples of yours like that, on a very recent release... Unfortunately the results of the ABAP formatter are backend release dependant.

**Comment by jelliottp** [comment]
> The ABAP formatter actually does format those examples of yours like that, on a very recent release... Unfortunately the results of the ABAP formatter are backend release dependant.

Id be fine with that for examples 1 & 2. But does it format like abap-cleaner does even for 3? That behavior seems very odd.

**Comment by jmgrassau** [comment]
Hi Josh, 

in my ADT, ABAP Formatter indeed puts this to upper case ```TEXT-01``` – and shows an error saying '"TEXT-01" is not a numbered text (for example: TEXT-001).' Doesn't it expect three digits on your system?

Example 2 is formatted by ABAP Formatter exactly as shown in your code, so it is indented, which I think makes sense and is consistent with formatting of ```BEGIN OF ... END OF``` blocks in other cases like ```TYPES```.

Regarding example 3 – yes, it is really unfortunate that we have to break a ```TYPES``` chain for an ```INCLUDE```! In my ADT, ABAP Formatter does this:

```ABAP
TYPES:
  BEGIN OF some_type.
    INCLUDE TYPE nested_type.
TYPES: field TYPE farr_contract_id,
  END OF some_type.
```

… which looks really messy to me. Your example …

```ABAP
TYPES:
  BEGIN OF some_type.
    INCLUDE TYPE nested_type.
    TYPES: field TYPE some_field,
  END OF some_type.
```

… actually looks better for my taste, but then, isn't it a bit inconsistent to have the ```TYPES``` keyword in two completely different positions? The second one is even indented further than ```END OF```!

That's why ABAP cleaner tries to have the ```TYPES``` keywords at the same vertical position (because they are at the same level of indentation), while moving the whole ```BEGIN OF ... END OF``` block a bit to the right, so it can be formatted as if it all were a single chain: 

```ABAP
TYPES: BEGIN OF some_type.
         INCLUDE TYPE nested_type.
TYPES:   field TYPE some_field,
       END OF some_type.
```

So, you could say it was a conscious decision against what ABAP Formatter does… 

Kind regards,
Jörg-Michael

**Comment by jelliottp** [comment]
> Hi Josh,
> 
> in my ADT, ABAP Formatter indeed puts this to upper case `TEXT-01` – and shows an error saying '"TEXT-01" is not a numbered text (for example: TEXT-001).' Doesn't it expect three digits on your system?

Yes, this is just a typo.

> 
> Example 2 is formatted by ABAP Formatter exactly as shown in your code, so it is indented, which I think makes sense and is consistent with formatting of `BEGIN OF ... END OF` blocks in other cases like `TYPES`.

I would prefer the indentation also, so this is just a difference of versions apparently.

> 
> Regarding example 3 – yes, it is really unfortunate that we have to break a `TYPES` chain for an `INCLUDE`! In my ADT, ABAP Formatter does this:
> 
> ```abap
> TYPES:
>   BEGIN OF some_type.
>     INCLUDE TYPE nested_type.
> TYPES: field TYPE farr_contract_id,
>   END OF some_type.
> ```
> 
> … which looks really messy to me. Your example …
> 
> ```abap
> TYPES:
>   BEGIN OF some_type.
>     INCLUDE TYPE nested_type.
>     TYPES: field TYPE some_field,
>   END OF some_type.
> ```
> 
> … actually looks better for my taste, but then, isn't it a bit inconsistent to have the `TYPES` keyword in two completely different positions? The second one is even indented further than `END OF`!
> 
> That's why ABAP cleaner tries to have the `TYPES` keywords at the same horizontal position (because they are at the same level of indentation), while moving the whole `BEGIN OF ... END OF` block a bit to the right, so it can be formatted as if it all were a single chain:
> 
> ```abap
> TYPES: BEGIN OF some_type.
>          INCLUDE TYPE nested_type.
> TYPES:   field TYPE some_field,
>        END OF some_type.
> ```
> 
> So, you could say it was a conscious decision against what ABAP Formatter does…
> 
> Kind regards, Jörg-Michael

Point 3 is certainly a unique situation. On one hand, yes, I would like all `TYPES` keywords in the same position, but I feel like the nested type is an exception, since it belongs inside the `BEGIN`/`END` block. I'm not sure I like it, but I have found that there is a "solution" which satisfies both abap-cleaner and the ATC checks we have for indentation in abapOpenChecks:
```
TYPES BEGIN OF some_type.
        INCLUDE TYPE nested_type.
TYPES   field TYPE some_field.
TYPES END OF some_type.
```
Not sure if others use this type of syntax, but I suppose it's a (not very obvious) compromise.

**Comment by jelliottp** [comment]
Closing this since there's a workaround and it's system version-dependent.

**Comment by jmgrassau** [comment]
Hi Josh, 

alright, thanks! Just to have some label assigned, I think this is somewhere in between "won't fix" and "no defect" …

Kind regards,
Jörg-Michael
