### ISSUE TITLE
"Align conditional expressions": `THROW` not aligned nicely in `SWITCH`

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/abap-cleaner#76]
Hi Jörg-Michael, the keyword `THROW` isn't aligned nicely when using `SWITCH`.

Actual:
```abap
  METHOD example.
    DATA var TYPE msgty.

    DATA(example) = SWITCH #( var
                              WHEN 'I' THEN '1'
                              WHEN 'E' THEN '2'
                              ELSE          THROW lcx_exception( ) ).
  ENDMETHOD.
```

Here's how I'd rather have it look like:

```abap
  METHOD example.
    DATA var TYPE msgty.

    DATA(example) = SWITCH #( var
                              WHEN 'I' THEN '1'
                              WHEN 'E' THEN '2'
                              ELSE     THROW lcx_exception( ) ).
  ENDMETHOD.
```

(Another possibility would be to align the previous values after `THEN` with the exception name, but I'd say this isn't necessary.)

Here are my settings:
![image](https://github.com/SAP/abap-cleaner/assets/72548231/9b0a5b66-0824-4264-872b-b90f23abc06f)

Thanks!

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

hm, I agree this doesn't look good from layout perspective; on the other hand, from logical perspective, this is correct: If someone uses 
![image](https://github.com/SAP/abap-cleaner/assets/79639298/1a8f081f-84c1-46e3-9dcc-4cd956699b4c)

they get:
```ABAP
    DATA(example) = SWITCH #( var
                              WHEN 'I' THEN
                                '1'
                              WHEN 'E' THEN
                                '2'
                              ELSE
                                THROW lcx_exception( ) ).
```

This doesn't look good, either, but it shows that logically, ```THROW ...``` is on the same level as ```'1'```, not on the same level as ```THEN```. 

So … probably this is a case for adding an option, so everyone can ponder layout versus logical aspects for themselves :-) 

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
Interesting, I didn't try that option yet. Personally, I would have formatted a multi-line layout differently:

```abap
    DATA(example) = SWITCH #( var
                              WHEN 'I' 
                                THEN '1'
                              WHEN 'E' 
                                THEN '2'
                              ELSE
                                THROW lcx_exception( ) ).
```

**Comment by jmgrassau** [comment]
Hi ConjuringCoffee, 

with these settings …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/27290ce7-0a8b-4d90-9cf3-cf611517d8d7)

you can indeed get the layout that you suggested. 

On the other hand, consider a case where two different types of exceptions are thrown – then ```THROW``` ends up in different positions:

```ABAP
    example = SWITCH #( var
                        WHEN 'I' 
                          THEN '1'
                        WHEN 'E' 
                          THEN THROW lcx_any_exception( )
                        ELSE
                          THROW lcx_other_exception( ) ).
```

I remember, when implementing this rule, there was always the feeling that with ```COND``` and ```SWITCH```, a "dissonance" remains between logic and layout …

Kind regards,
Jörg-Michael

**Comment by ConjuringCoffee** [comment]
I might have been odd in the beginning, but I can accept the logical perspective on this matter. 😉
