### ISSUE TITLE
'Align logical expression' does not recognize WHERE statement

### ISSUE THREAD

**Issue by FriedrGo** [SAP/abap-cleaner#79]
Dear All,

we are in the middle of cleaning up for a S/4 transition. Therefore we use quickfixes to amend some of the ATC findings. Afterwards we try to use ABAP-cleaner to make it nice.
The following statement (generated by a quickfix) is not picked up by the 'align logical expression' rule:

* => Determine tax code fully qualified
    SELECT * FROM YFT076M INTO LS_YFT076M UP TO 1 ROWS
 WHERE LANDD = IM_TAX_COUNTRY AND LAND = LV_LAND AND LAND1 = LV_LAND1 AND MWART = IM_IDOC_TAXCODE AND XEGDR = LS_VBRK-XEGDR AND TAXM1 = LS_MLAN-TAXM1 AND MTPOS = ' ' AND KTGRM = ' ' AND DATAB <= LV_BUDAT AND DATBI >= LV_BUDAT
 ORDER BY PRIMARY KEY .
 ENDSELECT.

I would have expected that line breaks are put into the code.

When breaking it down manually it does not move the 'AND' to the beginning of the line (so rule 'Move AND/ OR...' is ignored.

Can you help?

Best regards,
FriedGo

**Comment by ConjuringCoffee** [comment]
SQL statements are currently not covered by the ABAP Cleaner, see #6. 😉

**Comment by jmgrassau** [comment]
Hi FriedrGo, 

sorry to disappoint you for the moment – but as mentioned in #6, this is by no means out of scope for ABAP cleaner, but rather a big point on our wish list … 

Kind regards,
Jörg-Michael
