### ISSUE TITLE
Legacy internal table definitions, syntax error after refactoring

### ISSUE THREAD

**Issue by thebestabapdeveloper** [SAP/abap-cleaner#89]
Hello,

I am using the version 1.5.1 of AC .

It converts:
  DATA lt_val(50) OCCURS 0                 WITH HEADER LINE.
into:
  DATA lt_val TYPE c LENGTH 50 OCCURS 0                 WITH HEADER LINE.
which gives a syntax error.

Best regards.
Ty.

**Comment by jmgrassau** [comment]
Hi bestabapdeveloper, 

excellent, thank you for reporting this bug – it will be fixed in the next release!

Kind regards
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi bestabapdeveloper, 

thanks again – this should now be fixed with version 1.5.2 which was just released!

Kind regards,
Jörg-Michael

**Comment by thebestabapdeveloper** [comment]
Cheers.
