### ISSUE TITLE
Parsing error when code has functional methods as chained statements  

### ISSUE THREAD

**Issue by suynwa** [SAP/abap-cleaner#91]
When running abapCleaner on the following code snippet
```abap
class MAIN definition create public.

  public section.
    class-methods FOO importing PAR type I.

endclass.


class MAIN implementation.
  method FOO.
  endmethod.
endclass.

START-OF-SELECTION.
  MAIN=>FOO(:1 ), 2 ).
```
a parsing error is raised:

![image](https://github.com/SAP/abap-cleaner/assets/31508041/4c8f3fcd-83d6-42e7-916e-8aab1c631a81)

My expectation would be that abapCleaner splits the chained statement into multiple functional method calls:

```abap
MAIN=>FOO( 1 ).
MAIN=>FOO( 2 ).
```

Maybe the rule 'Unchain into multiple statements' can be enhanced. 

You can refer to the ABAP documentation https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abenchained_statements_guidl.htm#@@ITOC@@ABENCHAINED_STATEMENTS_GUIDL_1 for further guidelines on using chained statements.

**Comment by jmgrassau** [comment]
Hi Suhas, 

the next release will now show a more dedicated error message for this case:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/582211e0-1135-4b75-959a-cae08f0a286a)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Suhas, 

thanks again for bringing this up – version 1.5.4 with the improved error message was just released!

Kind regards,
Jörg-Michael
