### ISSUE TITLE
Use FINAL for immutable variables creates syntax error in case of method call

### ISSUE THREAD

**Issue by cgrail** [SAP/abap-cleaner#96]
Given is the following code:
```ABAP
class lcl_test definition create private.
  public section.
    types: begin of test,
             id   type sysuuid_x16,
             name type string,
           end of test.
    methods show_data.
endclass.


class lcl_test implementation.
  method show_data.
    try.
        data(test_data) = value test( id   = cl_system_uuid=>create_uuid_x16_static( )
                                      name = 'Test' ).
        cl_demo_output=>display( test_data ).
      catch cx_uuid_error.
        raise exception new cx_sovy_fsi_event_dispatcher( ).
    endtry.
  endmethod.
endclass.
```

When I run the ABAP Cleaner with the rule `Use FINAL for immutable variables` I will get a syntax error and the declaration type of the variable `test_data` will change from `DATA` to `FINAL`.

<img width="723" alt="Screenshot 2023-08-25 at 11 00 53" src="https://github.com/SAP/abap-cleaner/assets/5702278/96c929f5-7cf6-4f45-9b63-8a9f1570437e">

---

Manual solution is to either extract the creation of the id upfront:
```ABAP
        final(id) = cl_system_uuid=>create_uuid_x16_static( ).
        final(test_data) = value test( id   = id
                                       name = 'Test' ).
```
Or to move id generation to the last line:
```ABAP
        final(test_data) = value test( name = 'Test'
                                       id   = cl_system_uuid=>create_uuid_x16_static( ) ).
```

Which is weird, but works.

It would be great if you could add another check to either extract the result of inline calls into own variables or don't change the declaration type in that case.

**Comment by fabianlupa** [comment]
> Or to move id generation to the last line:

Seriously? The weird edge cases of the chosen expression implementation strike again :(

A variable inside the expression also works by the way:

```abap
        final(test_data) = value test( LET i = cl_system_uuid=>create_uuid_x16_static( ) IN
                                       id   = i
                                       name = 'Test' ).
```

In my opinion this should be fixed or at least documented somewhere. Having to account for this in abap-cleaner seems unreasonable, especially when it's not obvious what works and what does not.

**Comment by jmgrassau** [comment]
Hi Christian, 

that's an amazing finding indeed! And you can find more surprising examples, e.g. 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/84f43805-9592-4c7e-b2da-38c382cc37f8)

I shall ask colleagues from the ABAP compiler team about this. However, even if the compiler learns to deal with those cases at some point in the future, I think for the time being it would be best to prevent introducing ```FINAL``` whenever any method calls are found inside of constructor expressions on the right-hand side. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Christian and Fabian, 

with the next release, the workaround would be as mentioned: Whenever a method call is found _inside_ of a constructor expression, ```DATA``` is kept: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/f9b0422d-1572-4dba-a5a6-371286476770)

Hope this solves the issue, even if it does a bit too much; please let me know if you find cases which still cause a syntax error!

Kind regards,
Jörg-Michael

**Comment by suynwa** [comment]
> I shall ask colleagues from the ABAP compiler team about this. 
> 
Hi Jörg-Michael, done that already 👍🏼

**Comment by jmgrassau** [comment]
Hi Christian, Fabian and Suhas, 

thanks again for reporting this! The workaround is now in place with version 1.5.3, which was just released. Closing this issue for now, but if there are news from the ABAP compiler team on this, we could see if the workaround can be modified accordingly or even removed at some point. 

Kind regards,
Jörg-Michael

**Comment by cgrail** [comment]
Cool. Thanks a lot.
